=== Lucho00Cuba/docker/symphony/shared/perf/conf/dataloader/dataloader.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="DataLoader">
		<xs:annotation>
			<xs:documentation>The DataLoader root</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Properties" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Property" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Name" type="xs:string"/>
										<xs:choice>
											<xs:element name="Value" type="xs:string"/>
											<xs:element ref="List"/>
											<xs:element ref="Set"/>
											<xs:element ref="Map"/>
										</xs:choice>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Description" type="xs:string" minOccurs="0"/>
				<xs:element name="Reader">
					<xs:annotation>
						<xs:documentation>
							The plug-in Reader
						</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Properties" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Property" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Name" type="xs:string"/>
													<xs:choice>
														<xs:element name="Value" type="xs:string"/>
														<xs:element ref="List"/>
														<xs:element ref="Set"/>
														<xs:element ref="Map"/>
													</xs:choice>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Groups" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Group" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Name">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:enumeration value="preRead"/>
																<xs:enumeration value="hasMore"/>
																<xs:enumeration value="readRecords"/>
																<xs:enumeration value="postRead"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="Value">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:minLength value="1"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="Class">
							<xs:annotation>
								<xs:documentation>
									The name of Reader implements
								</xs:documentation>
							</xs:annotation>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
				<xs:element name="Writer">
					<xs:annotation>
						<xs:documentation>
							The common writer modle
						</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
                            <xs:element name="Properties" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Property" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Name" type="xs:string" />
													<xs:choice>
														<xs:element name="Value" type="xs:string" />
														<xs:element ref="List" />
														<xs:element ref="Set" />
														<xs:element ref="Map" />
													</xs:choice>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
                            <xs:element name="DataSource"
								type="xs:string" minOccurs="0" maxOccurs="1">
								<xs:annotation>
									<xs:documentation>
										The DataSource name
									</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="SQL"
								maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Statement">
											<xs:annotation>
												<xs:documentation>
													The insert sql
													statement
												</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="Field"
											maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute
													name="Name" type="xs:string" use="required">
													<xs:annotation>
														<xs:documentation>
															The key of
															input
															hashmap
														</xs:documentation>
													</xs:annotation>
												</xs:attribute>
												<xs:attribute
													name="Column" type="xs:string" use="required">
													<xs:annotation>
														<xs:documentation>
															The column
															name of
															table
														</xs:documentation>
													</xs:annotation>
												</xs:attribute>
												<xs:attribute
													name="Type" type="xs:string" use="optional" />
												<xs:attribute
													name="MaxLength" type="xs:integer" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element name="PK" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute
													name="Name" type="xs:string" use="required">
												</xs:attribute>
											</xs:complexType>
										</xs:element>
										<xs:element name="Extra" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute
													name="Name" type="xs:string" use="required">
												</xs:attribute>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="Input">
										<xs:annotation>
											<xs:documentation>
												The key of input
												hashmap. This is
												optional only for has
												multi sql statement
											</xs:documentation>
										</xs:annotation>
									</xs:attribute>
									<xs:attribute name="Update"
										type="xs:string">
										<xs:annotation>
											<xs:documentation>
												the key is used figure
												out insert model or
												update model
											</xs:documentation>
										</xs:annotation>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
							<xs:element name="Mappings" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Tables" minOccurs="0" maxOccurs="1">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Table" minOccurs="0" maxOccurs="unbounded">
														<xs:complexType>
															<xs:attribute name="Name" type="xs:string" use="required" />
															<xs:attribute name="Mapping" type="xs:string" use="required" />
															<xs:attribute name="Operation" type="xs:string" use="optional" />
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="Columns" minOccurs="0" maxOccurs="1">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Column" minOccurs="0" maxOccurs="unbounded">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="Field" minOccurs="0" maxOccurs="unbounded">
																	<xs:complexType>
																		<xs:attribute name="Name" type="xs:string" use="required" />
																		<xs:attribute name="Mapping" type="xs:string" use="required" />
																	</xs:complexType>
																</xs:element>
															</xs:sequence>	
															<xs:attribute name="Key" type= "xs:string" />
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							
							<xs:element name="Dependencies" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Dependency" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Keys" minOccurs="0" maxOccurs="1">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="Key" minOccurs="0" maxOccurs="unbounded">
																	<xs:complexType>
																		<xs:attribute name="Name" type="xs:string" use="required" />
																	</xs:complexType>
																</xs:element>
															</xs:sequence>												
														</xs:complexType>
													</xs:element>
													<xs:element name="Values" minOccurs="0" maxOccurs="1">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="Value" minOccurs="0" maxOccurs="unbounded">
																	<xs:complexType>
																		<xs:attribute name="Name" type="xs:string" use="required" />
																	</xs:complexType>
																</xs:element>
															</xs:sequence>												
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute name="Name" type= "xs:string"  use="required"/>
												<xs:attribute name="Class" type= "xs:string"  use="optional"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							
						</xs:sequence>
						<xs:attribute name="Type">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="JDBC" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="BatchSize" use="optional">
							<xs:annotation>
								<xs:documentation>
									The batch size for connection to
									commit
								</xs:documentation>
							</xs:annotation>
							<xs:simpleType>
								<xs:restriction base="xs:integer">
									<xs:minInclusive value="1" />
									<xs:maxInclusive value="10000" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="EnableRecover"
							type="xs:string" />
						<xs:attribute name="Class"
							type="xs:string">
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="List" type="ListType"/>
	<xs:complexType name="ListType">
		<xs:sequence>
			<xs:element name="Value" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="Set" type="SetType"/>
	<xs:complexType name="SetType">
		<xs:sequence>
			<xs:element name="Value" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="Map" type="MapType"/>
	<xs:complexType name="MapType">
		<xs:sequence>
			<xs:element name="Entry" type="MapEntryType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="MapEntryType">
		<xs:sequence>
			<xs:element name="Key" type="xs:string"/>
			<xs:element name="Value" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== Lucho00Cuba/docker/symphony/shared/perf/conf/dataloader/symchargebackloader.xml
<?xml version="1.0" encoding="UTF-8"?>
<DataLoader xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="dataloader.xsd">
 <!--
 Defined which Reader implement will be used to get data. The Class
 attribute refer the Class name or Reader implements. This Class can be
 developed by customer.
 -->
 <Description><![CDATA[ Calculate the hourly charge back value from PERF DB for consumer/resource group and load them into ES for the charge back reports.]]></Description>
 
 <Reader Class="com.platform.perf.dataloader.soam.esloader.ChargeBackReader">
     <Properties>
   <Property>
    <Name>DataLoaderName</Name>
    <Value>ChargeBackDataLoader</Value>
   </Property>
   <Property>
    <Name>DataSource</Name>
    <Value>ReportDB</Value>
   </Property>
   <!--
    Defined the name of which resource groups will be calculated.
    Leave it with blank or undefined means calculate for all resource groups.
    This is Optional -->
   <Property>
    <Name>ExcludedResourceGroups</Name>
    <Value>InternalResourceGroup,ManagementHosts,MapReduceInternalResourceGroup</Value>
   </Property>
  </Properties>
 </Reader>
 <!--
 Defined which Writer will be used to load the output of Reader into
 DataBase.
 Type   attribute is optional, it defined the DataBase operation type.
    By default, it is JDBC.
 BatchSize  Defined how many records will be committed into DataBase one time.
 -->
 <Writer Class="com.platform.perf.dataloader.es.ESWriter" Type="JDBC" BatchSize="100" EnableRecover="Y">
  <!--
  Defined the name of which DataSource will be used. This is Optional
  -->
  <DataSource>ESDB</DataSource>
 
  <!--
  The SQL statement will be defined in this element. If  The Field sub
  elements map the output of Reader to DataBase table. The Name attribute
  is the key of Reader output. The Column attribute is the column name of
  DataBase Table.
  -->
  <SQL Input="IBM-SYMPHONY-REPORT-CHARGE-BACK">
   <Statement><![CDATA[
     INSERT INTO IBM-SYMPHONY-REPORT-CHARGE-BACK(
     CLUSTER_NAME              ,
     CONSUMER_NAME             ,
     RESOURCE_GROUP            ,
     EVENT_TIME                ,
     CHARGEBACK_VALUE
   )VALUES(?,?,?,?,?)
   ]]>
   </Statement>
   <Field Name="CLUSTER_NAME" Column="CLUSTER_NAME"/>
   <Field Name="CONSUMER_NAME" Column="CONSUMER_NAME"/>
   <Field Name="RESOURCE_GROUP" Column="RESOURCE_GROUP"/>
   <Field Name="EVENT_TIME" Column="EVENT_TIME" Type="Timestamp"/>
   <Field Name="CHARGEBACK_VALUE" Column="CHARGEBACK_VALUE" Type="Numeric"/>
 
   <PK Name="CLUSTER_NAME"/>
   <PK Name="CONSUMER_NAME"/>
   <PK Name="RESOURCE_GROUP"/>
   <PK Name="EVENT_TIME"/>
  </SQL>
  <Mappings>
            <Tables>
                <Table Name="IBM-SYMPHONY-REPORT-CHARGE-BACK" Mapping="IBM-SYMPHONY-REPORT-CHARGE-BACK-%{yyyy.mm.dd}"/>
            </Tables>
   <Columns>
    <Column Key="IBM-SYMPHONY-REPORT-CHARGE-BACK">
     <Field Name="CLUSTER_NAME" Mapping="CLUSTER_NAME"/>
     <Field Name="CONSUMER_NAME" Mapping="CONSUMER_NAME"/>
     <Field Name="RESOURCE_GROUP" Mapping="RESOURCE_GROUP"/>
     <Field Name="EVENT_TIME" Mapping="EVENT_TIME"/>
     <Field Name="CHARGEBACK_VALUE" Mapping="CHARGEBACK_VALUE"/>
    </Column>
   </Columns>
  </Mappings>
 </Writer>
</DataLoader>

=== Lucho00Cuba/docker/symphony/shared/perf/conf/dataloader/egodynamicres.xml
<?xml version="1.0" encoding="UTF-8"?>
<DataLoader xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:noNamespaceSchemaLocation="dataloader.xsd" >
	
	<!-- 
	Defined which Reader implement will be used to get data. The Class
	attribute refer the Class name or Reader implements. This Class can be
	developed by customer. 
	-->
	<Reader Class="com.platform.perf.dataloader.ego.HostDynamicResLoader">
		<Properties> 
			<Property>
			 <!--The LoaderType's value indicates the loader type.
			  There are several value, for example 
			  0   sampling loader , that we should consider the data may lost.
			  1   file loader , that we should consider the data lost.
			  2   file loader , that we needn't consider the data lost.
			   --> 
				<Name>LoaderType</Name>
				<Value>0</Value>
			</Property> 
			<Property>
			 <!--We can use this value to multiply the interval value , and then
			   using the result to compare with the loader period cost.
			 -->			
				<Name>IntervalPercentage</Name>
				<Value>0.8</Value>
			</Property> 
		</Properties>
	</Reader>
	
	<!-- 
	Defined which Writer will be used to load the output of Reader into
	DataBase. 
	Type 		attribute is optional, it defined the DataBase operation type.
				By default, it is JDBC.
	BatchSize 	Defined how many records will be committed into DataBase one time.
     EnableRecover: this tag is set to enable or disable automatic data loss protection. 
	-->
	<Writer Type="JDBC" BatchSize="1" EnableRecover="Y">
		<!-- 
		Defined the name of which DataSource will be used. This is Optional
		-->
		<DataSource>ReportDB</DataSource>
		
		<!--
		The SQL statement will be defined in this element. If  The Field sub
		elements map the output of Reader to DataBase table. The Name attribute
		is the key of Reader output. The Column attribute is the column name of
		DataBase Table.
		-->
		<SQL Input="RESOURCE_METRICS">
   	<Statement><![CDATA[
   	INSERT INTO RESOURCE_METRICS(
   	RESOURCE_NAME,
   	RESOURCE_TYPE,
   	ATTRIBUTE_NAME,
   	ATTRIBUTE_TYPE,
   	ATTRIBUTE_VALUE_STR,
   	ATTRIBUTE_VALUE_NUM,
   	TIME_STAMP,
	TIME_STAMP_GMT,
	CLUSTER_NAME
   	)VALUES(?,?,?,?,?,?,?,?,?)
   	]]>
   	</Statement>
   	<Field Name="resName" Column=" RESOURCE_NAME" Type="String"/>
   	<Field Name="resType" Column=" RESOURCE_TYPE" Type="String"/>
   	<Field Name="attName" Column=" ATTRIBUTE_NAME" Type="String"/>
   	<Field Name="attType" Column=" ATTRIBUTE_TYPE" Type="String"/>
   	<Field Name="attValue_str" Column=" ATTRIBUTE_VALUE_STR" Type="String"/>
   	<Field Name="attValue_num" Column=" ATTRIBUTE_VALUE_NUM" Type="Float"/>
   	<Field Name="time" Column=" TIME_STAMP" Type="Timestamp"/>
	<Field Name="GMT" Column="TIME_STAMP_GMT" Type="Long"/>
	<Field Name="clustername" Column="CLUSTER_NAME" Type="String"/>
  	</SQL>
		
	</Writer>
</DataLoader>

=== Lucho00Cuba/docker/symphony/shared/perf/conf/dataloader/symsessionhistloader.xml
<?xml version="1.0" encoding="UTF-8"?>
<DataLoader xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="dataloader.xsd">
	<!-- 
	Defined which Reader implement will be used to get data. The Class
	attribute refer the Class name or Reader implements. This Class can be
	developed by customer. 
	-->
	<Reader Class="com.platform.perf.dataloader.soam.SessionFDataReaderMgr">
	    <Properties>
			<Property>
				<Name>SOAPTimeOut</Name>
				<!--The 180 is in seconds-->
				<Value>180</Value>
			</Property>
			<Property>
				<Name>HistoryLoad</Name>
				<!--The 3 is in days-->
				<Value>3</Value>
			</Property>			
			<Property>
				<Name>Apps</Name>
				<Set>
					<!--Value>symping</Value-->
				</Set>
			</Property>
			<Property>
				<Name>RetryLimit</Name>
				<!--This value is in times-->
				<Value>1</Value>
			</Property>
		</Properties>
	</Reader>	
	<!-- 
	Defined which Writer will be used to load the output of Reader into
	DataBase. 
	Type 		attribute is optional, it defined the DataBase operation type.
				By default, it is JDBC.
	BatchSize 	Defined how many records will be committed into DataBase one time.
	-->
	<Writer Type="JDBC" BatchSize="1">
		<!-- 
		Defined the name of which DataSource will be used. This is Optional
		-->
		<DataSource>ReportDB</DataSource>
		
		<!--
		The SQL statement will be defined in this element. If  The Field sub
		elements map the output of Reader to DataBase table. The Name attribute
		is the key of Reader output. The Column attribute is the column name of
		DataBase Table.
		-->
	<SQL Input="SESSION_HISTORY">
   	<Statement><![CDATA[     
	  INSERT INTO SESSION_HISTORY( 
	  CLUSTER_NAME             ,
      TIME_STAMP                ,                   
      TIME_STAMP_GMT            ,      
      SESSION_ID                ,             
      SESSION_NAME              ,             
      APP_NAME                  ,              
      CONSUMER_NAME             ,          
      PRIORITY                  ,          
      SESSION_STATE             ,        
      NUM_TASK_PENDING          ,       
      NUM_TASK_RUNNING          ,       
      NUM_TASK_DONE             ,       
      NUM_TASK_ERROR            ,      
      NUM_TASK_CANCELED         ,     
      SERVICE_INSTANCES         ,  
      SUBMISSION_USER           ,
      REASON                    ,
      ABORT_SESSION_IF_TASK_FAIL,
      RECOVERABLE               ,
      SESSION_TYPE              ,
      CREATE_TIME               ,     
      LAST_ERROR_TIME           ,
      TASK_RETRY_LIMIT          ,
      SERVICE                   ,      
      PERSIST_SESSION_HISTORY   ,
      PERSIST_TASK_HISTORY      ,
	  END_TIME                  ,
	  SESSION_RETRY_LIMIT       ,
	  TOTAL_UNSUCCESS_TASKRUNS        ,
	  TOTAL_UNSUCCESS_TASKSRUNTIME       ,
	  TOTAL_TASKS_RUNTIME              ,
	  TOTAL_INPUT_SIZE            ,
	  TOTAL_OUTPUT_SIZE           ,
	  TOTAL_TASKS_SUBMIT2START_TIME        ,
	  COMMON_DATA_SIZE          ,
	  SESSION_TAG               ,
	  PROTOCOL_VERSION          ,
	  SYMPHONY_VERSION          ,
	  SESSION_BINDING_FAILURES     ,
	  SESSION_UPDATE_FAILURES              ,    
      NUM_COMMON_DATA_UPDATES              ,
      TOTAL_COMMON_DATA_UPDATE_SIZE         ,
      COMPRESSION_ENABLED          ,
      COMMON_DATA_COMPRESSED ,
      RAW_COMMON_DATA_SIZE            ,
      COMPRESSION_THRESHOLD        ,
      DIRECT_DATA_TRANSFER_ENABLED,
      SSN_ABORT_IFCLIENT_DISCONNECT,
      SSN_DISCARD_RESULT_ONDELIVERY,
      PREEMPTIVE,
      CLIENT_VERSION,
      CLIENT_HOST_NAME,
      CLIENT_IP_ADDRESS,
      CLIENT_OS_USER_NAME,
      SERVICE_TO_SLOT_RATIO,
      RESOURCE_GROUP_FILTER,
      PREEMPTION_RANK,
      TASKS_INTERRUPTED_BY_PREEMPT,
      PREEMPT_TIME,
      TASKS_INTERRUPTED_BY_RECLAIM,
      RECLAIM_TIME,
      SESSION_METADATA,
      NUM_TASK_YIELDED,
      NUM_TASK_RESUMING,
      PARENT_ID,
      ROOT_SESSION_ID,
      TASK_DISPATCH_ORDER,
      POLICY_TAG_PATH,
      SESSION_TIMEOUT,
      TASK_EXECUTION_TIMEOUT
	)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
   	]]>
   	</Statement>
	<Field Name="clustername" Column="CLUSTER_NAME"/>
   	<Field Name="TIME_STAMP" Column="TIME_STAMP"/>
   	<Field Name="TIME_STAMP_GMT" Column="TIME_STAMP_GMT"/>
   	<Field Name="SESSION_ID" Column="SESSION_ID"/>
   	<Field Name="SESSION_NAME" Column="SESSION_NAME"/>
   	<Field Name="APP_NAME" Column="APP_NAME"/>
   	<Field Name="CONSUMER_NAME" Column="CONSUMER_NAME"/>
   	<Field Name="PRIORITY" Column="PRIORITY"/>
   	<Field Name="SESSION_STATE" Column="SESSION_STATE"/>
   	<Field Name="NUM_TASK_PENDING" Column="NUM_TASK_PENDING"/>
    <Field Name="NUM_TASK_RUNNING" Column="NUM_TASK_RUNNING"/>
        
   	<Field Name="NUM_TASK_DONE" Column="NUM_TASK_DONE"/>
   	<Field Name="NUM_TASK_ERROR" Column="NUM_TASK_ERROR"/>	
   	<Field Name="NUM_TASK_CANCELED" Column="NUM_TASK_CANCELED"/>
   	<Field Name="SERVICE_INSTANCES" Column="SERVICE_INSTANCES"/>
   	<Field Name="SUBMISSION_USER" Column="SUBMISSION_USER"/>
   	<Field Name="ABORT_REASON" Column="REASON"/>
   	<Field Name="ABORT_SESSION_IF_TASK_FAIL" Column="ABORT_SESSION_IF_TASK_FAIL"/>
   	<Field Name="RECOVERABLE" Column="RECOVERABLE"/>
   	<Field Name="SESSION_TYPE" Column="SESSION_TYPE"/>
   	<Field Name="CREATE_TIME" Column="CREATE_TIME"/>
   	<Field Name="LAST_ERROR_TIME" Column="LAST_ERROR_TIME"/>
   	<Field Name="TASK_RETRY_LIMIT" Column="TASK_RETRY_LIMIT"/>
   	<Field Name="SERVICE" Column="SERVICE"/>   	
   	<Field Name="PERSIST_SESSION_HISTORY" Column="PERSIST_SESSION_HISTORY"/>
   	<Field Name="PERSIST_TASK_HISTORY" Column="PERSIST_TASK_HISTORY"/>
	
	<!--Symphony 3.2-->
	<Field Name="END_TIME" Column="END_TIME"/>
	<Field Name="SESSION_RETRY_LIMIT" Column="SESSION_RETRY_LIMIT"/>
	<Field Name="TOT_NUM_RERUN_TASK" Column="TOTAL_UNSUCCESS_TASKRUNS"/>
	
	<Field Name="TOT_TASK_RERUN_TIME" Column="TOTAL_UNSUCCESS_TASKSRUNTIME"/>	
	<Field Name="TOT_RUN_TIME" Column="TOTAL_TASKS_RUNTIME"/> 
	<Field Name="TOT_INPUT_SIZE" Column="TOTAL_INPUT_SIZE"/>
	
	<Field Name="TOT_OUTPUT_SIZE" Column="TOTAL_OUTPUT_SIZE"/> 
	<Field Name="TOT_TASK_WAIT_TIME" Column="TOTAL_TASKS_SUBMIT2START_TIME"/>
	<Field Name="COMMON_DATA_SIZE" Column="COMMON_DATA_SIZE"/>
	
	<Field Name="SESSION_TAG" Column="SESSION_TAG"/> 
	<Field Name="PROTOCOL_VERSION" Column="PROTOCOL_VERSION"/> 
	<Field Name="SSM_VERSION" Column="SYMPHONY_VERSION"/>
	
	<!--Symphony 4.1-->
	<Field Name="SESSION_BINDING_FAILURES" Column="SESSION_BINDING_FAILURES"/>
    <Field Name="SESSION_UPDATE_FAILURES" Column="SESSION_UPDATE_FAILURES"/>
	<Field Name="NUM_COMMON_DATA_UPDATES" Column="NUM_COMMON_DATA_UPDATES"/>
	<Field Name="TOTAL_COMMON_DATA_UPDATE_SIZE" Column="TOTAL_COMMON_DATA_UPDATE_SIZE"/>
	<Field Name="COMPRESSION_ENABLED" Column="COMPRESSION_ENABLED"/>
	<Field Name="COMMON_DATA_COMPRESSED" Column="COMMON_DATA_COMPRESSED"/>
	<Field Name="RAW_COMMON_DATA_SIZE" Column="RAW_COMMON_DATA_SIZE"/>
	<Field Name="COMPRESSION_THRESHOLD" Column="COMPRESSION_THRESHOLD"/>
	<Field Name="DIRECT_DATA_TRANSFER_ENABLED" Column="DIRECT_DATA_TRANSFER_ENABLED"/>
	
	<!--Symphony 5.0-->
	<Field Name="SESSION_ABORT_IF_CLIENT_DISCONNECT" Column="SSN_ABORT_IFCLIENT_DISCONNECT"/>
	<Field Name="SESSION_DISCARD_RESULTS_ON_DELIVERY" Column="SSN_DISCARD_RESULT_ONDELIVERY"/>
	<Field Name="PREEMPTIVE" Column="PREEMPTIVE"/>
	<Field Name="CLIENT_VERSION" Column="CLIENT_VERSION"/>
	<Field Name="CLIENT_HOST_NAME" Column="CLIENT_HOST_NAME"/>
	<Field Name="CLIENT_IP_ADDRESS" Column="CLIENT_IP_ADDRESS"/>
	<Field Name="CLIENT_OS_USER_NAME" Column="CLIENT_OS_USER_NAME"/>
	<Field Name="SERVICE_TO_SLOT_RATIO" Column="SERVICE_TO_SLOT_RATIO"/>
	<Field Name="RESOURCE_GROUP_FILTER" Column="RESOURCE_GROUP_FILTER"/>
	<Field Name="PREEMPTION_RANK" Column="PREEMPTION_RANK"/>
        <Field Name="TASKS_INTERRUPTED_BY_PREEMPT" Column="TASKS_INTERRUPTED_BY_PREEMPT"/>
        <Field Name="PREEMPT_TIME" Column="PREEMPT_TIME"/>
        <Field Name="TASKS_INTERRUPTED_BY_RECLAIM" Column="TASKS_INTERRUPTED_BY_RECLAIM"/>
        <Field Name="RECLAIM_TIME" Column="RECLAIM_TIME"/>
        
        <!--Symphony 7.1.0-->
        <Field Name="SESSION_METADATA" Column="SESSION_METADATA"/>
        <Field Name="NUM_TASK_YIELDED" Column="NUM_TASK_YIELDED"/>
		<Field Name="NUM_TASK_RESUMING" Column="NUM_TASK_RESUMING"/>
		<Field Name="PARENT_ID" Column="PARENT_ID"/>
		<Field Name="ROOT_SESSION_ID" Column="ROOT_SESSION_ID"/>
		<Field Name="TASK_DISPATCH_ORDER" Column="TASK_DISPATCH_ORDER"/>
		<Field Name="POLICY_TAG_PATH" Column="POLICY_TAG_PATH"/>
		<Field Name="SESSION_TIMEOUT" Column="SESSION_TIMEOUT"/>
		<Field Name="TASK_EXECUTION_TIMEOUT" Column="TASK_EXECUTION_TIMEOUT"/>
  	</SQL>		
	</Writer>
</DataLoader>

=== Lucho00Cuba/docker/symphony/shared/perf/conf/dataloader/egoevents.xml
<?xml version="1.0" encoding="UTF-8"?>
<DataLoader xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:noNamespaceSchemaLocation="dataloader.xsd" >
	
	<!-- 
	Defined which Reader implement will be used to get data. The Class
	attribute refer the Class name or Reader implements. This Class can be
	developed by customer. 
	-->
	<Reader Class="com.platform.perf.dataloader.ego.allocreqevent.Egoeventdataloader">
		<Properties>
			<Property>
				<Name>RetryLimit</Name>
					<!--The value is the limit for retry count when the read lines include '\0' character-->
					<Value>1</Value>
			</Property>
		</Properties>
	</Reader>
	
	<!-- 
	Defined which Writer will be used to load the output of Reader into
	DataBase. 
	Type 		attribute is optional, it defined the DataBase operation type.
				By default, it is JDBC.
	BatchSize 	Defined how many records will be committed into DataBase one time.
	-->
	<Writer Type="JDBC" BatchSize="1">
		<!-- 
		Defined the name of which DataSource will be used. This is Optional
		-->
		<DataSource>ReportDB</DataSource>
		
		<!--
		The SQL statement will be defined in this element. If  The Field sub
		elements map the output of Reader to DataBase table. The Name attribute
		is the key of Reader output. The Column attribute is the column name of
		DataBase Table.
		-->
	<SQL Input="ALLOCATION_EVENT">
   	<Statement><![CDATA[
   	INSERT INTO ALLOCATION_EVENT (
   	EVENT_TYPE,
	EVENT_TIME,
	EVENT_TIME_GMT,
	ALLOCATION_ID,
	ALLOCATION_NAME,
	CLIENT,
	CONSUMER_NAME,
	RESOURCE_GROUP,
	FILTER,
	MIN_SLOT,
	MAX_SLOT,
	FLAGS,
	TILE,
	HOSTS,
	BLHOSTS,
	RESOURCE_GROUP_LISTS,
	USER_NAME,
	CONTAINER_ID,
	FILE_POSITION,
	CLUSTER_NAME
   	)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
   	]]>
   	</Statement>
   	<Field Name="EVENT_TYPE" Column="EVENT_TYPE"/>
   	<Field Name="EVENT_TIME" Column="EVENT_TIME" Type="Timestamp"/>
   	<Field Name="EVENT_TIME_GMT" Column="EVENT_TIME_GMT" Type="Numeric"/>
   	<Field Name="ALLOCATION_ID" Column="ALLOCATION_ID" />
   	<Field Name="ALLOCATION_NAME" Column="ALLOCATION_NAME"/>
   	<Field Name="CLIENT" Column="CLIENT"/>
   	<Field Name="CONSUMER_NAME" Column="CONSUMER_NAME"/>
   	<Field Name="RESOURCE_GROUP" Column="RESOURCE_GROUP"/>
   	<Field Name="FILTER" Column="FILTER"/>
   	<Field Name="MIN_SLOT" Column="MIN_SLOT" Type="Numeric"/>
   	<Field Name="MAX_SLOT" Column="MAX_SLOT" Type="Numeric"/>
   	<Field Name="FLAGS" Column="FLAGS" Type="Numeric"/>
   	<Field Name="TILE" Column="TILE" Type="Numeric"/>   	
   	<Field Name="HOSTS" Column="HOSTS"/>
   	<Field Name="BLHOSTS" Column="BLHOSTS"/>
   	<Field Name="RESOURCE_GROUP_LISTS" Column="RESOURCE_GROUP_LISTS"/>
   	<Field Name="USER_NAME" Column="USER_NAME"/>
   	<Field Name="CONTAINER_ID" Column="CONTAINER_ID" Type="Numeric"/>
   	<Field Name="FILE_POSITION" Column="FILE_POSITION" Type="Numeric"/>
    <Field Name="clustername" Column="CLUSTER_NAME"/>
  	</SQL>
		
	</Writer>
</DataLoader>
