=== Lucho00Cuba/docker/symphony/shared/perf/conf/dataloader/dataloader.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="DataLoader">
		<xs:annotation>
			<xs:documentation>The DataLoader root</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Properties" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Property" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Name" type="xs:string"/>
										<xs:choice>
											<xs:element name="Value" type="xs:string"/>
											<xs:element ref="List"/>
											<xs:element ref="Set"/>
											<xs:element ref="Map"/>
										</xs:choice>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Description" type="xs:string" minOccurs="0"/>
				<xs:element name="Reader">
					<xs:annotation>
						<xs:documentation>
							The plug-in Reader
						</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Properties" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Property" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Name" type="xs:string"/>
													<xs:choice>
														<xs:element name="Value" type="xs:string"/>
														<xs:element ref="List"/>
														<xs:element ref="Set"/>
														<xs:element ref="Map"/>
													</xs:choice>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Groups" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Group" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Name">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:enumeration value="preRead"/>
																<xs:enumeration value="hasMore"/>
																<xs:enumeration value="readRecords"/>
																<xs:enumeration value="postRead"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="Value">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:minLength value="1"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="Class">
							<xs:annotation>
								<xs:documentation>
									The name of Reader implements
								</xs:documentation>
							</xs:annotation>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
				<xs:element name="Writer">
					<xs:annotation>
						<xs:documentation>
							The common writer modle
						</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
                            <xs:element name="Properties" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Property" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Name" type="xs:string" />
													<xs:choice>
														<xs:element name="Value" type="xs:string" />
														<xs:element ref="List" />
														<xs:element ref="Set" />
														<xs:element ref="Map" />
													</xs:choice>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
                            <xs:element name="DataSource"
								type="xs:string" minOccurs="0" maxOccurs="1">
								<xs:annotation>
									<xs:documentation>
										The DataSource name
									</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="SQL"
								maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Statement">
											<xs:annotation>
												<xs:documentation>
													The insert sql
													statement
												</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="Field"
											maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute
													name="Name" type="xs:string" use="required">
													<xs:annotation>
														<xs:documentation>
															The key of
															input
															hashmap
														</xs:documentation>
													</xs:annotation>
												</xs:attribute>
												<xs:attribute
													name="Column" type="xs:string" use="required">
													<xs:annotation>
														<xs:documentation>
															The column
															name of
															table
														</xs:documentation>
													</xs:annotation>
												</xs:attribute>
												<xs:attribute
													name="Type" type="xs:string" use="optional" />
												<xs:attribute
													name="MaxLength" type="xs:integer" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element name="PK" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute
													name="Name" type="xs:string" use="required">
												</xs:attribute>
											</xs:complexType>
										</xs:element>
										<xs:element name="Extra" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute
													name="Name" type="xs:string" use="required">
												</xs:attribute>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="Input">
										<xs:annotation>
											<xs:documentation>
												The key of input
												hashmap. This is
												optional only for has
												multi sql statement
											</xs:documentation>
										</xs:annotation>
									</xs:attribute>
									<xs:attribute name="Update"
										type="xs:string">
										<xs:annotation>
											<xs:documentation>
												the key is used figure
												out insert model or
												update model
											</xs:documentation>
										</xs:annotation>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
							<xs:element name="Mappings" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Tables" minOccurs="0" maxOccurs="1">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Table" minOccurs="0" maxOccurs="unbounded">
														<xs:complexType>
															<xs:attribute name="Name" type="xs:string" use="required" />
															<xs:attribute name="Mapping" type="xs:string" use="required" />
															<xs:attribute name="Operation" type="xs:string" use="optional" />
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="Columns" minOccurs="0" maxOccurs="1">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Column" minOccurs="0" maxOccurs="unbounded">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="Field" minOccurs="0" maxOccurs="unbounded">
																	<xs:complexType>
																		<xs:attribute name="Name" type="xs:string" use="required" />
																		<xs:attribute name="Mapping" type="xs:string" use="required" />
																	</xs:complexType>
																</xs:element>
															</xs:sequence>	
															<xs:attribute name="Key" type= "xs:string" />
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							
							<xs:element name="Dependencies" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Dependency" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Keys" minOccurs="0" maxOccurs="1">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="Key" minOccurs="0" maxOccurs="unbounded">
																	<xs:complexType>
																		<xs:attribute name="Name" type="xs:string" use="required" />
																	</xs:complexType>
																</xs:element>
															</xs:sequence>												
														</xs:complexType>
													</xs:element>
													<xs:element name="Values" minOccurs="0" maxOccurs="1">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="Value" minOccurs="0" maxOccurs="unbounded">
																	<xs:complexType>
																		<xs:attribute name="Name" type="xs:string" use="required" />
																	</xs:complexType>
																</xs:element>
															</xs:sequence>												
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute name="Name" type= "xs:string"  use="required"/>
												<xs:attribute name="Class" type= "xs:string"  use="optional"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							
						</xs:sequence>
						<xs:attribute name="Type">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="JDBC" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="BatchSize" use="optional">
							<xs:annotation>
								<xs:documentation>
									The batch size for connection to
									commit
								</xs:documentation>
							</xs:annotation>
							<xs:simpleType>
								<xs:restriction base="xs:integer">
									<xs:minInclusive value="1" />
									<xs:maxInclusive value="10000" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="EnableRecover"
							type="xs:string" />
						<xs:attribute name="Class"
							type="xs:string">
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="List" type="ListType"/>
	<xs:complexType name="ListType">
		<xs:sequence>
			<xs:element name="Value" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="Set" type="SetType"/>
	<xs:complexType name="SetType">
		<xs:sequence>
			<xs:element name="Value" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="Map" type="MapType"/>
	<xs:complexType name="MapType">
		<xs:sequence>
			<xs:element name="Entry" type="MapEntryType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="MapEntryType">
		<xs:sequence>
			<xs:element name="Key" type="xs:string"/>
			<xs:element name="Value" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== Lucho00Cuba/docker/symphony/shared/perf/conf/dataloader/symtaskhistloader.xml
<?xml version="1.0" encoding="UTF-8"?>
<DataLoader xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="dataloader.xsd">
	<!-- 
	Defines the reader used to get data. The Class
	attribute refers to the class name or reader name. This class can be
	developed by you. 
	-->
	<Reader Class="com.platform.perf.dataloader.soam.TaskFDataReaderMgr">
	    <Properties>
			<Property>
				<Name>SOAPTimeOut</Name>
				<!--The value is in seconds-->
				<Value>180</Value>
			</Property>
			<Property>
				<Name>HistoryLoad</Name>
				<!--This value is in days-->
				<Value>3</Value>
			</Property>			
			<Property>
				<Name>Apps</Name>
				<Set>
					<!--Value>symping</Value-->
				</Set>
			</Property>
			<Property>
				<Name>RetryLimit</Name>
				<!--This value is in times-->
				<Value>1</Value>
			</Property>
		</Properties>
	</Reader>	
	<!-- 
	Defines the writer that is used to load the output of the reader into the
	database. The Type attribute is optional and defines the database operation type. The default is JDBC.
	BatchSize defines how many records will be committed into the database at one time.
	-->
	<Writer Type="JDBC" BatchSize="100">
		<!-- 
		Defines the name of the data source that will be used. This is optional.
		-->
		<DataSource>ReportDB</DataSource>
		<!--
		This element defines the SQL statement if the Field sub-elements map the output of the reader to the database table. 
		The Name attribute is the key for the reader output. The Column attribute is the column name of
		the database table.
		-->
		<SQL Input="TASK_ATTRIBUTES">
			<Statement><![CDATA[     
	  INSERT INTO TASK_ATTRIBUTES( 
      TIME_STAMP          ,                   
      TIME_STAMP_GMT      ,      
      TASK_ID             ,
	  SESSION_ID          ,
      APP_NAME            ,
      TASK_STATE          ,
      SUBMIT_TIME         ,
      START_TIME          ,
      END_TIME            ,
      EXEC_HOST           ,
      INPUT_SIZE          ,
      OUTPUT_SIZE         ,
      SERVICE_PID         ,
      RERUN_COUNT         ,
      TASK_TAG            ,
      SYMPHONY_VERSION    ,
	  PROTOCOL_VERSION    ,
	  CLUSTER_NAME        ,
	  LAST_FAILURE_REASON ,
	  NUM_COMMON_DATA_UPDATES             ,
      COMPRESSION_ENABLED         ,
      INPUT_COMPRESSED   ,
      OUTPUT_COMPRESSED  ,
      RAW_INPUT_SIZE              ,
      RAW_OUTPUT_SIZE             ,
      COMPRESSION_THRESHOLD       ,
      DIRECT_DATA_TRANSFER_ENABLED,
      CHILD_SESSIONS,
      SLOT_OWNER,
      TASK_PRIORITY,
      CPU_TIME,
      PHY_MEMORY_USAGE,
      SWAP_USAGE,
      RESOURCE_GROUP,
      TASK_ON_INVOKE_TIMEOUT
	)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
   	]]></Statement>
			<Field Name="TIME_STAMP" Column="TIME_STAMP"/>
			<Field Name="TIME_STAMP_GMT" Column="TIME_STAMP_GMT"/>
			<Field Name="TASK_ID" Column="TASK_ID"/>
			<Field Name="SESSION_ID" Column="SESSION_ID"/>
			<Field Name="APP_NAME" Column="APP_NAME"/>
			<Field Name="TASK_STATE" Column="TASK_STATE"/>
			<Field Name="SUBMIT_TIME" Column="SUBMIT_TIME"/>
			<Field Name="START_TIME" Column="START_TIME"/>
			<Field Name="END_TIME" Column="END_TIME"/>
			<Field Name="EXEC_HOST" Column="EXEC_HOST"/>
			<Field Name="INPUT_SIZE" Column="INPUT_SIZE"/>
			<Field Name="OUTPUT_SIZE" Column="OUTPUT_SIZE"/>
			<Field Name="SERVICE_PID" Column="SERVICE_PID"/>
			<Field Name="RERUN_COUNT" Column="RERUN_COUNT"/>
                   
		    <Field Name="TASK_TAG" Column="TASK_TAG"/> 	
			<!-- SSM VERSION and PROTOCOL VERSION -->
			<Field Name="SSM_VERSION" Column="SYMPHONY_VERSION"/>
			<Field Name="PROTOCOL_VERSION" Column="PROTOCOL_VERSION"/>
			<Field Name="clustername" Column="CLUSTER_NAME"/>
		    <Field Name="LAST_FAILURE_REASON" Column="LAST_FAILURE_REASON"/>
		    <!--Symphony 4.1-->		    
            <Field Name="NUM_COMMON_DATA_UPDATES" Column="NUM_COMMON_DATA_UPDATES"/>
            <Field Name="COMPRESSION_ENABLED" Column="COMPRESSION_ENABLED" Type="Boolean"/>
            <Field Name="INPUT_COMPRESSED" Column="INPUT_COMPRESSED" Type="Boolean"/>
            <Field Name="OUTPUT_COMPRESSED" Column="OUTPUT_COMPRESSED" Type="Boolean"/>
            <Field Name="RAW_INPUT_SIZE" Column="RAW_INPUT_SIZE"/>
            <Field Name="RAW_OUTPUT_SIZE" Column="RAW_OUTPUT_SIZE"/>
            <Field Name="COMPRESSION_THRESHOLD" Column="COMPRESSION_THRESHOLD"/>
            <Field Name="DIRECT_DATA_TRANSFER_ENABLED" Column="DIRECT_DATA_TRANSFER_ENABLED" Type="Boolean" />	
            <Field Name="CHILD_SESSIONS" Column="CHILD_SESSIONS"/>
            <Field Name="SLOT_OWNER" Column="SLOT_OWNER"/>
            <Field Name="TASK_PRIORITY" Column="TASK_PRIORITY"/>
            <Field Name="CPU_TIME" Column="CPU_TIME"/>
            <Field Name="PHY_MEMORY_USAGE" Column="PHY_MEMORY_USAGE"/>
            <Field Name="SWAP_USAGE" Column="SWAP_USAGE"/>	  
            <Field Name="RESOURCE_GROUP" Column="RESOURCE_GROUP"/>
            <Field Name="TASK_ON_INVOKE_TIMEOUT" Column="TASK_ON_INVOKE_TIMEOUT"/>
		</SQL>
	</Writer>
</DataLoader>
