=== Lucho00Cuba/docker/symphony/shared/perf/conf/plc.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:loader="http://www.ibm.com/perf/2006/01/loader" targetNamespace="http://www.ibm.com/perf/2006/01/loader" elementFormDefault="qualified">
	<xs:element name="PLC">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Version" type="xs:string"/>
				<xs:element name="Port">
					<xs:simpleType>
						<xs:restriction base="xs:integer">
							<xs:minInclusive value="1"/>
							<xs:maxInclusive value="65535"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="MaxLoadingThread">
					<xs:simpleType>
						<xs:restriction base="xs:integer">
							<xs:maxInclusive value="20"/>
							<xs:minInclusive value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="PLCDir">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Recover">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="EnableAutoLoad" type="xs:boolean" default="true"/>
							<xs:element name="RecoverInterval" default="5">
								<xs:simpleType>
									<xs:restriction base="xs:long">
										<xs:maxInclusive value="65535"/>
										<xs:minInclusive value="1"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="MaxThread" default="10">
								<xs:simpleType>
									<xs:restriction base="xs:integer">
										<xs:maxInclusive value="50"/>
										<xs:minInclusive value="1"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="MaxFileSize" default="100" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:integer">
										<xs:maxInclusive value="1000"/>
										<xs:minInclusive value="1"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="DLPPurgerInterval" default="00:30">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="4"/>
										<xs:maxLength value="7"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="DLPPurgerDuration" default="14">
								<xs:simpleType>
									<xs:restriction base="xs:integer">
										<xs:maxInclusive value="31"/>
										<xs:minInclusive value="1"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="EnableDLPPurger" type="xs:boolean" default="true"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Lucho00Cuba/docker/symphony/shared/perf/conf/plc.xml
<?xml version="1.0" encoding="UTF-8"?>
<PLC xmlns="http://www.ibm.com/perf/2006/01/loader"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="http://www.ibm.com/perf/2006/01/loader plc.xsd">
	 
	<!-- The version of the loader controller. -->
	<Version>4.0</Version>
	
	<!-- The port number of the loader controller that will listen to the CLI. -->
	<Port>4046</Port>
	
	<!-- The maximum number of threads for running data loader plug-in instances. -->
	<MaxLoadingThread>20</MaxLoadingThread>
	
	<!-- The directory containing the data loader configuration files. This directory is located in EGO_TOP/perf/conf. -->
	<PLCDir>plc</PLCDir>
	
    <!--Recover define the behavior of recover DLP data -->
	<Recover>		
		<!-- Does enable auto load data from file to database. If you leave it blank, 
		 the default value true will be used. -->
		<EnableAutoLoad>true</EnableAutoLoad>

		<!-- The interval duration of RecoverJob executing. The unit is second.  If you leave it blank, 
		 the default value 60 will be used.-->
		<RecoverInterval>60</RecoverInterval>
		
		<!-- The maximum number of threads for recovering data from file to database when "EnableAutoLoad" is set to "true". If you leave it blank, the default value 10 will be used. -->
		<MaxThread>10</MaxThread>
		
		<!-- The maximum size of recover file. The unit is MB. If you leave it blank, 
		 the default value 100 will be used. -->
		<MaxFileSize>100</MaxFileSize>
		
		<!--The expression showes the period of the DLPPurgerJob executing. It showes the hour and minute or repeat period.
			The format for this expression is like :
			*:15, *:*[5], *:*[15], *[15], *[5] and 12:15.
			If you leave it blank, the default value 00:30 will be used.
			-->
		<DLPPurgerInterval>00:30</DLPPurgerInterval>
		
		<!-- The duration of the backup data will keep. If you leave it blank, 
		 the default value 14 will be used. -->		
		<DLPPurgerDuration>14</DLPPurgerDuration>
		
		<!-- Does enable auto purger the DLP backup data. If you leave it blank, 
		 the default value true will be used. -->
		<EnableDLPPurger>true</EnableDLPPurger>
		
	</Recover>
</PLC>
