=== Lucho00Cuba/docker/symphony/shared/gui/conf/asp_portal/portal/useracl/users_role_mapping.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Authorization">
		<xs:annotation>
			<xs:documentation>Authorization root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="AclActorList" minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>AclActorList element</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="AclActor" minOccurs="0" maxOccurs="unbounded">
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="AclMember">
		<xs:complexType mixed="true">
			<xs:attribute name="type" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="user"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="AclActorList">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="AclActor" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="AclActor">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Info"/>
				<xs:element ref="AclMember" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="id" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="CommonUser"/>
						<xs:enumeration value="OrgLeader"/>
						<xs:enumeration value="DepLeader"/>
						<xs:enumeration value="Admin"/>
						<xs:enumeration value="VipUser"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="type" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="group"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="Info">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Common User"/>
				<xs:enumeration value="Org Leader"/>
				<xs:enumeration value="Dep Leader"/>
				<xs:enumeration value="Administrator"/>
				<xs:enumeration value="Privileged Execution for Admin"/>
				<xs:enumeration value="VIP User"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
</xs:schema>

=== Lucho00Cuba/docker/symphony/shared/gui/conf/asp_portal/portal/useracl/users_role_mapping.xml
<?xml version="1.0" encoding="UTF-8"?>

<Authorization xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="users_role_mapping.xsd">  
  <AclActorList> 
    <AclActor id="Admin" type="group"> 
      <Info>Administrator</Info>  
      <AclMember type="user">lsfadmin</AclMember>  
      <AclMember type="user">Admin</AclMember>  
    </AclActor>  
    <AclActor id="VipUser" type="group"> 
      <Info>VIP User</Info> 
    </AclActor>  
    <AclActor id="OrgLeader" type="group"> 
      <Info>Org Leader</Info> 
    </AclActor>  
    <AclActor id="DepLeader" type="group"> 
      <Info>Dep Leader</Info> 
    </AclActor>  
    <AclActor id="CommonUser" type="group"> 
      <Info>Common User</Info>  
      <AclMember type="user">user1</AclMember>
    </AclActor> 
  </AclActorList> 
</Authorization>
