=== Lucho00Cuba/docker/symphony/shared/gui/conf/navigation/pmc_tab.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="http://www.platform.com/gui/pmc_tab" 
	xmlns:tns="http://www.platform.com/gui/pmc_tab" 
	elementFormDefault="qualified">

    <element name="Tab" type="tns:TabType"></element>
    
    <complexType name="TabType">
    	<sequence>
    		<element name="TabGroups" type="tns:TabGroupsType" minOccurs="1" maxOccurs="1"></element>
    		<element name="TabItems" type="tns:TabItemsType" minOccurs="1" maxOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="TabItemsType">
    	<sequence>
    		<element name="TabItem" type="tns:TabItemType" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>
    
    <complexType name="TabGroupsType">
    	<sequence>
    		<element name="TabGroup" type="tns:TabGroupType" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <complexType name="TabGroupType">
    	<sequence></sequence>
    	<attribute name="id" type="string"></attribute>
    	<attribute name="tabIds" type="string"></attribute>
    	<attribute name="activeIndex" type="int" default="-1"></attribute>
    </complexType>

    <complexType name="TabItemType">
    	<sequence>
    		<element name="Datasource" type="string" minOccurs="0" maxOccurs="1"></element>
    	</sequence>
    	<attribute name="id" type="string"></attribute>
    	<attribute name="label" type="string"></attribute>
    	<attribute name="status" type="string"></attribute>
    	<attribute name="disabled" type="string"></attribute>
    	<attribute name="type" type="string"></attribute>
    	<attribute name="url" type="string"></attribute>
    	<attribute name="layoutSourceId" type="string"></attribute>
    </complexType>
</schema>

=== Lucho00Cuba/docker/symphony/shared/gui/conf/navigation/pmc_tab_SYM.xml
<?xml version="1.0" encoding="UTF-8"?>
<Tab xmlns="http://www.platform.com/gui/pmc_tab" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.platform.com/gui/pmc_tab pmc_tab.xsd">
	<TabGroups>
		<TabGroup id="appBottomTabGroup"
			tabIds="symAppProperties,symAppSessions,symAppServices,symAppProfiles,symAppPerformance,symAppSLBlockedHosts,symAppBlockedHosts,symAppResources,symAppPackage,symPhysicalApps" />
		<TabGroup id="sessionTabGroup"
			tabIds="SymSessionSummary,sessionTasks,sessionPerformance" />
		<TabGroup id="symTaskTabGroup"
			tabIds="symTaskSummary,symTaskAttempts" />
		
	</TabGroups>
	

	<TabItems>
		
		<!-- workload application -->
		<TabItem id="SymSessionSummary" label="@{pmc.tab.sym.workload.session.summary}"
			status="display" disabled="false" type="iframe"
			url="/symgui/sym/session/tosymsessionsummary.controller">
			<Datasource></Datasource>
		</TabItem>

		<TabItem id="sessionTasks" label="@{pmc.tab.sym.workload.session.tasks}"
			status="display" disabled="false" type="iframe"
			url="/symgui/sym/task/toTask.controller">
			<Datasource></Datasource>
		</TabItem>

		<TabItem id="sessionPerformance" label="@{pmc.tab.sym.workload.session.performance}"
			status="display" disabled="false" type="iframe"
			url="/soamgui/getTaskInfo.controller?&amp;viewType=charts&amp;isEmbed=true">
			<Datasource></Datasource>
		</TabItem>

		

		<!-- Sympnony workload applicaiton tabs -->
		<TabItem id="symAppProperties" label="@{pmc.tab.sym.workload.application.proerties}"
			status="display" disabled="false" type="iframe"
			url="/symgui/sym/application/toApplicationProperties.controller">
			<Datasource></Datasource>
		</TabItem>
		<TabItem id="symAppServices" label="@{pmc.tab.sym.workload.application.services}"
			status="display" disabled="false" type="iframe"
			url="/symgui/sym/application/toSymAppServiceList.controller">
			<Datasource></Datasource>
		</TabItem>
		<TabItem id="symAppSessions" label="@{pmc.tab.sym.workload.application.sessions}"
			status="display" disabled="false" type="iframe"
			url="/symgui/sym/session/tosessions.controller">
			<Datasource></Datasource>
		</TabItem>
		<TabItem id="symAppProfiles" label="@{pmc.tab.sym.workload.application.profile}"
			status="display" disabled="false" type="iframe"
			url="/soamgui/getApplicationProfile.controller?&amp;viewType=profile&amp;isEmbed=true">
			<Datasource></Datasource>
		</TabItem>
		<TabItem id="symAppPerformance" label="@{pmc.tab.sym.workload.application.performance}"
			status="display" disabled="false" type="iframe"
			url="/soamgui/getApplicationPerformance.controller?&amp;viewType=charts&amp;isEmbed=true">
			<Datasource></Datasource>
		</TabItem>
		<TabItem id="symAppSLBlockedHosts" label="@{pmc.tab.sym.workload.application.sl.blockedhosts}"
			status="display" disabled="false" type="iframe"
			url="/symgui/sym/application/toSLBlockedHostList.controller">
			<Datasource></Datasource>
		</TabItem>
		<TabItem id="symAppBlockedHosts" label="@{pmc.tab.sym.workload.application.blockedhosts}"
			status="display" disabled="false" type="iframe"
			url="/symgui/sym/application/toBlockedHostList.controller">
			<Datasource></Datasource>
		</TabItem>
		<TabItem id="symAppResources" label="@{pmc.tab.sym.workload.application.resources}"
			status="display" disabled="false" type="iframe"
			url="/symgui/sym/application/toResourceList.controller">
			<Datasource></Datasource>
		</TabItem>
		<TabItem id="symAppPackage"
			label="@{pmc.tab.sym.workload.application.package.downloads}" status="display"
			disabled="false" type="iframe"
			url="/symgui/sym/application/toDownloadPackageList.controller">
			<Datasource></Datasource>
		</TabItem>
		<TabItem id="symPhysicalApps"
			label="@{pmc.tab.sym.workload.application.physicalApps}" status="display"
			disabled="false" type="iframe"
			url="/symgui/sym/application/toPhysAppsList.controller">
			<Datasource></Datasource>
		</TabItem>
		<TabItem id="symTaskSummary" label="@{pmc.tab.sym.workload.task.summary}"
			status="display" disabled="false" type="iframe"
			url="/symgui/sym/task/toTaskSummry.controller">
			<Datasource></Datasource>
		</TabItem>
		<TabItem id="symTaskAttempts" label="@{pmc.tab.sym.workload.task.attempts}"
			status="display" disabled="false" type="iframe"
			url="/symgui/sym/task/toTaskAttempts.controller">
			<Datasource></Datasource>
		</TabItem>		
		
	</TabItems>
	
	
</Tab>
