=== Lucho00Cuba/docker/symphony/shared/gui/conf/navigation/pmc_tree.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="http://www.platform.com/gui/pmc_tree" 
	xmlns:tns="http://www.platform.com/gui/pmc_tree" 
	elementFormDefault="qualified">

    <element name="Tree" type="tns:TreeType"></element>
    
    <complexType name="TreeType">
    	<sequence>
    		<element name="TreeItem" type="tns:TreeItemType"
    			minOccurs="0" maxOccurs="unbounded">
    		</element>
    	</sequence>
    </complexType>

    <complexType name="TreeItemType">
    	<sequence>
    		<element name="Nodes" type="tns:NodesType" minOccurs="0" maxOccurs="1"></element>
    	</sequence>
    	<attribute name="id" type="string"></attribute>
    </complexType>

    <complexType name="NodesType">
    	<sequence>
    		<element name="Node" type="tns:NodeType" minOccurs="1" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <complexType name="NodeType">
    	<sequence>
    		<element ref="tns:Nodes" minOccurs="0" maxOccurs="1"></element>
    	</sequence>
    	<attribute name="id" type="string"></attribute>
    	<attribute name="label" type="string"></attribute>
    	<attribute name="icon" type="string"></attribute>
    	<attribute name="status" type="string"></attribute>
    	<attribute name="url" type="string"></attribute>
    	<attribute name="layoutSourceId" type="string"></attribute>
    	<attribute name="tabGroup" type="string"></attribute>
    	<attribute name="helpGroupId" type="string"></attribute>
    	<attribute name="highlightTabId" type="string"></attribute>
    	<attribute name="childUrl" type="string"></attribute>
    	<attribute name="param" type="string"></attribute>
    	<attribute name="aclResource" type="string"></attribute>
    	<attribute name="aclPermission">
    		<simpleType>
    			<restriction base="int">
    				<minInclusive value="1"></minInclusive>
    				<maxExclusive value="7"></maxExclusive>
    			</restriction>
    		</simpleType>
    	</attribute>
    	<attribute name="disabled" type="boolean"></attribute>
    </complexType>

    <element name="Nodes" type="tns:NodesType"></element>

    <element name="Node" type="tns:NodeType"></element>

    <element name="TreeItem" type="tns:TreeItemType"></element>
</schema>

=== Lucho00Cuba/docker/symphony/shared/gui/conf/asp_portal/report/navigation/pmc_tree.xml
<?xml version="1.0" encoding="UTF-8"?>
<Tree xmlns="http://www.platform.com/gui/pmc_tree"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.platform.com/gui/pmc_tree pmc_tree.xsd">

	<TreeItem id="jobsTreeSource">
		<Nodes>
			<Node id="jobSubmission" label="@{pmc.tree.node.submissionforms.label}" icon="" status="" 
				url="/platform/application/toLoadAllForms.controller" 
				layoutSourceId="allJobs" tabGroup="" highlightTabId="" childUrl="/platform/application/loadAllFromsTreeNode.controller">
			</Node>
			<Node id="Jobs" label="@{pmc.tree.node.jobs.label}" icon="" status="" url=""
				layoutSourceId="jobs" tabGroup="" highlightTabId=""/>
			<Node id="JobFlows" label="@{pmc.tree.node.jobflows.label}" icon="" status=""
				 tabGroup="jobFlowsTabGroup" highlightTabId="jobFlowsSummary">
				<Nodes>
					<Node id="ppm_flowByUser" label="@{pmc.tree.node.jobflows.filter.user}" icon="" status=""
						layoutSourceId="ppm_flowByUser_layout" tabGroup="definitionTabGroup" highlightTabId=""  childUrl="../ppm/common/doGetFlowByUserNodes.controller"/>
					<Node id="ppm_flowByState" label="@{pmc.tree.node.jobflows.filter.state}" icon="" status=""
						layoutSourceId="ppm_flowByState_layout" tabGroup="instanceTabGroup" highlightTabId="" childUrl="../ppm/common/doGetFlowByStateNodes.controller"/>
				</Nodes>
			</Node>
			<Node id="JobData" label="@{pmc.tree.node.jobdata.label}" icon="" status="" url=""
				layoutSourceId="" tabGroup="" highlightTabId="">
				<Nodes>
					<Node id="JobDirectories" label="@{pmc.tree.node.jobdirectories.label}" icon="" status=""
						url="" layoutSourceId="jobdirectories" tabGroup="" highlightTabId=""/>
					<Node id="JobFlowDirectories" label="@{pmc.tree.node.jobflowdir.label}" status="" layoutSourceId="jobFlowDataLayout" />
					<Node id="JobDataExplore" label="@{pmc.tree.node.jobdataexplore.label}" icon="" status=""
						url="/platform/job/sharedDirectoryAction.controller"
						layoutSourceId="" tabGroup="" highlightTabId=""/>
				</Nodes>
			</Node>
			<Node id="JobConsoles" label="@{pmc.tree.node.jobconsoles.label}" icon="" status=""
				url="/platform/vnc/VNCList.controller" layoutSourceId="" tabGroup="" highlightTabId=""/>
		</Nodes>
	</TreeItem>

	<TreeItem id="resourceTreeSource">
		<Nodes>
			<Node id="DashboardNode" label="@{pmc.tree.node.dashboard.label}" icon="" status=""  
				 url="/platform/dashboard/toResDashboard.controller" aclResource="System" aclPermission="3">
			</Node>
			<Node id="Hosts" label="@{pmc.tree.node.hosts.label}" icon="" status=""  
				url="" layoutSourceId="hostLayout" tabGroup="hostTabGroup" highlightTabId=""
				aclResource="All Hosts" aclPermission="1">
			</Node>
			<Node id="ApplicationTemplates" label="@{pmc.tree.node.applicationtemplates.label}" status="" 
						url="/platform/application/toLoadAppTemplates.controller" 
						aclResource="APP_TEMPLATE_-ALL_TEMPLATES_NODE" aclPermission="1"/>
			<Node id="licenseUsages" label="@{pmc.tree.node.licenses.label}" url="../pls/toLicenseSummary.controller"
				aclResource="License Scheduler" aclPermission="1" childUrl="../pls/toLicenseTree.controller">
			</Node>
		</Nodes>
	</TreeItem>
	
	<TreeItem id="settingsTreeSource">
		<Nodes>
			<Node id="users" label="@{pmc.tree.node.settings.users.label}" url="" aclResource="System" aclPermission="3" layoutSourceId="userGroupLayout">
				<Nodes>
					<Node id="userGroups" label="@{pmc.tree.node.settings.userGroups.label}" layoutSourceId="userGroupLayout"/>
					<Node id="userRoles" label="@{pmc.tree.node.settings.userRoles.label}" layoutSourceId="userRoleLayout" />
				</Nodes>
			</Node>
			<Node id="logo_and_color" label="@{pmc.tree.node.logo_color.label}" status="" 
						url="/platform/framework/portal/toConfigureAppearance.controller" aclResource="System" aclPermission="3" />
			<Node id="pageSettings" label="@{pmc.tree.node.pageSettings.label}" status=""
						url="/platform/pac/configurations/toJobPageSetting.controller" aclResource="System" aclPermission="3" />
			
		</Nodes>
	</TreeItem>

	<TreeItem id="reportsTreeSource">
		<Nodes>
			<Node id="Resource_Usage" label="@{pmc.tree.node.perfreports.resourceusage.label}" status="" 
                                url="/report/reportListingAction.controller?folder=ResourceUsage&amp;reportType=2"/>
			<Node id="CPU_Monitor" label="@{pmc.tree.node.perfreports.cpumonitor.label}" status="" 
                                url="/report/reportListingAction.controller?folder=JobSlotUsage&amp;reportType=2"/>
			<Node id="Done_Job_Monitor" label="@{pmc.tree.node.perfreports.donejobmonitor.label}" status="" 
                                url="/report/reportListingAction.controller?folder=DoneJobStatus&amp;reportType=2"/>
                        <Node id="Run_Job_Monitor" label="@{pmc.tree.node.perfreports.runjobmonitor.label}" status="" 
                                url="/report/reportListingAction.controller?folder=RunJobStatus&amp;reportType=2"/>
			<Node id="License_Usage" label="@{pmc.tree.node.perfreports.licenseusage.label}" status="" 
                                url="/report/reportListingAction.controller?folder=LicenseUsage&amp;reportType=2"/>
                        <Node id="SAN_Usage" label="@{pmc.tree.node.perfreports.sanusage.label}" status="" 
                                url="/report/reportListingAction.controller?folder=SANUsage&amp;reportType=2"/>
			<Node id="Queue_Accounting" label="@{pmc.tree.node.perfreports.queueaccounting.label}" status="" 
                                url="/report/reportListingAction.controller?folder=QueueAccounting&amp;reportType=2"/>
		</Nodes>
	</TreeItem>

	<TreeItem id="reportInstanceTreeSource">
                <Nodes>
                        <Node id="Resource_Usage_Cluster" label="@{pmc.tree.node.perfreports.instance.resourceusage.cluster.label}" status="" 
                                url="/report/reportInstanceManageAction.controller?directory=<reportInstanceDirectory>&amp;reportType=2&amp;dispatch=reportInstanceLIST"/>
			<Node id="SAN_Usage_Usage" label="@{pmc.tree.node.perfreports.instance.sanusage.label}" status="" 
                                url="/report/reportInstanceManageAction.controller?directory=<reportInstanceDirectory>&amp;reportType=2&amp;dispatch=reportInstanceLIST"/>
                </Nodes>
        </TreeItem>
</Tree>

=== Lucho00Cuba/docker/symphony/shared/gui/conf/navigation/pmc_tree.xml
<?xml version="1.0" encoding="UTF-8"?>
<Tree xmlns="http://www.platform.com/gui/pmc_tree" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.platform.com/gui/pmc_tree pmc_tree.xsd">
	<TreeItem id="workloadTreeSource">
		<Nodes>
			<Node id="lsf" label="@{pmc.tree.node.lsf.label}" icon="" status="" url=""
				layoutSourceId="" tabGroup="" highlightTabId="" aclResource="Batch_job_info"
				aclPermission="1">
				<Nodes>
					<Node id="lsfJob" label="@{pmc.tree.node.lsfJob.label}" icon="" status=""
						url="" layoutSourceId="lsfJobLayout"
						tabGroup="" highlightTabId="" aclResource="Batch_job_info"
						aclPermission="1">
					</Node>
				</Nodes>
			</Node>
			<Node id="ego" label="@{pmc.tree.node.ego.label}" icon="" status="" url=""
				layoutSourceId="" tabGroup="" highlightTabId="" aclResource="Main_service"
				aclPermission="1">
				<Nodes>
					<Node id="egoService" label="@{pmc.tree.node.egoService.label}" icon="" status=""
						url="" layoutSourceId="egoServiceLayout" tabGroup=""
						highlightTabId="" aclResource="Main_service" aclPermission="1">
					</Node>
					<Node id="egoProfile" label="@{pmc.tree.node.egoProfile.label}" icon="" status=""
						url="" layoutSourceId="egoProfileLayout" tabGroup=""
						highlightTabId="" aclResource="Main_service" aclPermission="1">
					</Node>
				</Nodes>
			</Node>
		</Nodes>
	</TreeItem>

	<TreeItem id="resourceTreeSource">
		<Nodes>
			<Node id="host" label="@{pmc.tree.node.resource.label}" icon="" status="" url=""
				layoutSourceId="" tabGroup="" highlightTabId="" aclResource="Main_host"
				aclPermission="1">
				<Nodes>
					<Node id="hostListIcon" label="@{pmc.tree.node.hostListIcon.label}" icon=""
						status="" url="" layoutSourceId="resourceHostLayout" tabGroup=""
						highlightTabId="" aclResource="Main_host" aclPermission="1">
					</Node>
				   <Node id="allHostList" label="@{pmc.tree.node.allHostList.label}" icon="" 
				       status="" url="" layoutSourceId="allHostLayout"
					tabGroup="" highlightTabId="" aclResource="Main_host"
					aclPermission="1">
				   </Node>
				</Nodes>
			</Node>
            <Node id="consumer" label="@{pmc.tree.node.consumer.label}" icon="" status="" url=""
                layoutSourceId="consumerListLayout" tabGroup="" highlightTabId=""
                aclResource="Consumer_plan_consumer" aclPermission="1">
            </Node>
			<Node id="resourcePlan_slot" label="@{pmc.tree.node.resourceGroup.label}" icon="" status=""
				url="" layoutSourceId="" tabGroup="" highlightTabId=""
				aclResource="Consumer_plan_consumer" aclPermission="1">
				<Nodes>
					<Node id="rg" label="@{pmc.tree.node.subResourceGroup.label}" icon="" status="" url=""
						layoutSourceId="resourceGroupLayout" tabGroup="" highlightTabId=""
						aclResource="Main_rGroup" aclPermission="1">
					</Node>
					<Node id="resourcePlanSchedule" label="@{pmc.tree.node.resourcePlan.label}" icon=""
						status="" url="" layoutSourceId="resourcePlanLayout" tabGroup=""
						highlightTabId="" aclResource="Consumer_plan_resourceplan"
						aclPermission="1">
					</Node>
					<Node id="resourceAllocation" label="@{pmc.tree.node.resourceAllo.label}"
						icon="" status="" url="" layoutSourceId="resourceAlloLayout"
						tabGroup="" highlightTabId="" aclResource="Consumer_plan_allocationResource"
						aclPermission="1">
					</Node>
					<Node id="resourceMDSAllocation" label="@{pmc.tree.node.resourceMDSAllo.label}"
						icon="" status="" url="" layoutSourceId="resourceMDSAlloLayout"
						tabGroup="" highlightTabId="" aclResource="Consumer_plan_allocationResource"
						aclPermission="1">
					</Node>
				</Nodes>
			</Node>
			<Node id="resourcePlan_mds" label="@{pmc.tree.node.resourceGroupMDS.label}" icon="" status=""
                url="" layoutSourceId="" tabGroup="" highlightTabId=""
                aclResource="Consumer_plan_consumer" aclPermission="1">
                <Nodes>
                    <Node id="mdsrg" label="@{pmc.tree.node.mdsResourceGroup.label}" icon="" status="" url=""
                        layoutSourceId="mdsResourceGroupLayout" tabGroup="" highlightTabId=""
                        aclResource="Main_rGroup" aclPermission="1">
                    </Node>
                    <Node id="MDSResourcePlan" label="@{pmc.tree.node.MDSResourcePlan.label}" icon="" status="" url=""
                        layoutSourceId="MDSResourcePlanLayout" tabGroup="" highlightTabId=""
                        aclResource="Consumer_plan_activeResourcePlan" aclPermission="1">
                    </Node>
                </Nodes>
            </Node>
			<Node id="servicePackage" label="@{pmc.tree.node.servicePackage.label}" icon=""
				status="" url="" layoutSourceId="" tabGroup="" highlightTabId=""
				aclResource="ServicePackageListView" aclPermission="1">
				<Nodes>
					<Node id="repositoryPackage" label="@{pmc.tree.node.repositoryRegion.label}"
						icon="" status="" url="" layoutSourceId="serviceRegionLayout"
						tabGroup="" highlightTabId="" aclResource="Main_RS_Region"
						aclPermission="1">
					</Node>
				</Nodes>
			</Node>
		</Nodes>
	</TreeItem>

	<TreeItem id="systemTreeSource">
		<Nodes>
			<Node id="entitlement" label="@{pmc.tree.node.entitlement.label}" status=""
				url="" layoutSourceId="entitlementLayout" tabGroup=""
				highlightTabId="" aclResource="Main_clusterSetting_license"
				aclPermission="1" />
			<Node id="cluster" label="@{pmc.tree.node.cluster.label}" status="" url=""
				layoutSourceId="" tabGroup="" highlightTabId="" aclResource="Main_clusterSetting"
				aclPermission="1">
				<Nodes>
					<Node id="summary" label="@{pmc.tree.node.summary.label}" icon="" status="" url=""
						layoutSourceId="clusterSummaryLayout" tabGroup="" highlightTabId=""
						aclResource="Main_clusterSetting_summary" aclPermission="1">
					</Node>
					<Node id="properties" label="@{pmc.tree.node.property.label}" icon="" status=""
						url="" layoutSourceId="clusterPropertyLayout" tabGroup=""
						highlightTabId="" aclResource="Main_clusterSetting_user"
						aclPermission="1">
					</Node>
					<Node id="masterFailover" label="@{pmc.tree.node.masterFailover.label}" icon=""
						status="" url="" layoutSourceId="masterFailoverLayout" tabGroup=""
						highlightTabId="Main_clusterSetting_mastercandidate" aclResource=""
						aclPermission="1">
					</Node>
				</Nodes>
			</Node>
			<Node id="user" label="@{pmc.tree.node.user.label}" status="" url="" layoutSourceId=""
				tabGroup="" highlightTabId="" aclResource="Main_user" aclPermission="1">
				<Nodes>
					<Node id="account" label="@{pmc.tree.node.account.label}" icon="" status="" url=""
						layoutSourceId="userAccountsLayout" tabGroup="" highlightTabId=""
						aclResource="Main_user" aclPermission="1">
					</Node>
					<Node id="role" label="@{pmc.tree.node.role.label}" icon="" status="" url=""
						layoutSourceId="userRoleLayout" tabGroup="" highlightTabId=""
						aclResource="Main_user_role" aclPermission="1">
					</Node>
				</Nodes>
			</Node>
		</Nodes>
	</TreeItem>

	<TreeItem id="eventAndReportTreeSource">
		<Nodes>
			<Node id="standardReport" label="@{pmc.tree.node.standarReport.label}" status=""
				url="" layoutSourceId="standarReportLayout" tabGroup=""
				highlightTabId="" aclResource="Main_perf_standard" aclPermission="1" />
			<Node id="customReport" label="@{pmc.tree.node.customerReport.label}" status="" url=""
				layoutSourceId="customReportLayout" tabGroup="" highlightTabId=""
				aclResource="Main_perf_custom" aclPermission="1" />
			<Node id="systemLog" label="@{pmc.tree.node.systemLog.label}" status="" url=""
				layoutSourceId="systemReportLayout" tabGroup="" highlightTabId=""
				aclResource="Main_logretrieve" aclPermission="1" />
			<Node id="explorerReport" label="@{pmc.tree.node.explorerReport.label}" status="" url=""
				layoutSourceId="" tabGroup="" highlightTabId="" aclResource="Main_explorer_report"
				aclPermission="1">
				<Nodes>
					<Node id="explorerDashboard" label="@{pmc.tree.node.explorerDashboard.label}" icon="" status="" url=""
						layoutSourceId="explorerDashboardLayout" tabGroup="" highlightTabId=""
						aclResource="Main_explorer_report" aclPermission="1">
					</Node>
					<Node id="explorerChart" label="@{pmc.tree.node.explorerChart.label}" icon="" status=""
						url="" layoutSourceId="explorerChartLayout" tabGroup=""
						highlightTabId="" aclResource="Main_explorer_report"
						aclPermission="1">
					</Node>
				</Nodes>
			</Node>
		</Nodes>
	</TreeItem>

	<TreeItem id="harvesting">
		<Nodes>
			<Node id="harvestingHost" label="@{pmc.tree.node.harvestiong.host.label}" status="" url=""
				layoutSourceId="harvestingHostLayout" tabGroup="" highlightTabId=""
				aclResource="Main_harvesting_host" aclPermission="1" />
			<Node id="configure" label="@{pmc.tree.node.harvestiong.conf.label}" status="" url=""
				layoutSourceId="harvestingConfLayout" tabGroup="" highlightTabId=""
				aclResource="Main_harvesting_conf" aclPermission="1" />
			<Node id="vmResources" label="@{pmc.tree.node.harvestiong.vmResource.label}" status=""
				url="" layoutSourceId="harvestingVMResourceLayout" tabGroup=""
				highlightTabId="" aclResource="Main_harvesting_host" aclPermission="1" />
		</Nodes>
	</TreeItem>
</Tree>

=== Lucho00Cuba/docker/symphony/shared/gui/conf/navigation/pmc_tree_SYM.xml
<?xml version="1.0" encoding="UTF-8"?>
<Tree xmlns="http://www.platform.com/gui/pmc_tree" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.platform.com/gui/pmc_tree pmc_tree.xsd">
	<TreeItem id="workloadTreeSource">
		<Nodes>
			<Node id="symphony" label="@{pmc.tree.node.symphony.label}" icon="" status="" url=""
				layoutSourceId="" tabGroup="" highlightTabId="" aclResource="Main_SOAM"
				aclPermission="1">
				<Nodes>
					<Node id="symphonyApp" label="@{pmc.tree.node.applications.label}" icon="" status=""
						url="" layoutSourceId="applicationLayout" tabGroup=""
						highlightTabId="applicationLayout" aclResource="Main_session"
						aclPermission="1">
					</Node>
					<Node id="profile" label="@{pmc.tree.node.appProfiles.label}" icon=""
						status="" url="" layoutSourceId="symAppProfileLayout" tabGroup=""
						highlightTabId="symAppProfileLayout" aclResource="Configuration"
						aclPermission="1">
					</Node>
					<Node id="deprofile" label="@{pmc.tree.node.appProfiles.label}" icon=""
						status="" url="" layoutSourceId="desymAppProfileLayout" tabGroup=""
						highlightTabId="symAppProfileLayout" aclResource="Configuration"
						aclPermission="1">
					</Node>
				</Nodes>
			</Node>
		</Nodes>
	</TreeItem>

	<TreeItem id="resourceTreeSource">
		<Nodes>
			<Node id="servicePackage" label="@{pmc.tree.node.servicePackage.label}" icon=""
				status="" url="" layoutSourceId="" tabGroup="" highlightTabId=""
				aclResource="ServicePackageListView" aclPermission="1">
				<Nodes>
					<Node id="symServicePackage" label="@{pmc.tree.node.symServicePackage.label}"
						icon="" status="" url="" layoutSourceId="servicePackageLayout"
						tabGroup="" highlightTabId="" aclResource="ServicePackageListView"
						aclPermission="1">
					</Node>
					<Node id="desymServicePackage" label="@{pmc.tree.node.symServicePackage.label}"
						icon="" status="" url="" layoutSourceId="deservicePackageLayout"
						tabGroup="" highlightTabId="" aclResource="ServicePackageListView"
						aclPermission="1" helpGroupId="symServicePackages">
					</Node>
				</Nodes>
			</Node>
		</Nodes>
	</TreeItem>
</Tree>
