=== Lucho00Cuba/docker/symphony/shared/gui/conf/navigation/pmc_layout.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="http://www.platform.com/gui/pmc_layout" 
	xmlns:tns="http://www.platform.com/gui/pmc_layout" 
	elementFormDefault="qualified">
    <element name="Layout" type="tns:LayoutType"></element>
    
    <complexType name="LayoutType">
    	<sequence>
    		<element name="LayoutItem" type="tns:LayoutItemType" minOccurs="1" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <complexType name="LayoutItemType">
    	<sequence>
    		<element name="LayoutUnits" type="tns:LayoutUnitsType" minOccurs="0" maxOccurs="1"></element>
    	</sequence>
    	<attribute name="id" type="string"></attribute>
    	<attribute name="minWidth" type="string"></attribute>
    	<attribute name="minHeight" type="string"></attribute>
    	<attribute name="isPersist" type="string"></attribute>
    </complexType>

    <complexType name="LayoutUnitsType">
    	<sequence>
    		<element name="LayoutUnit" type="tns:LayoutUnitType" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <complexType name="LayoutUnitType">
    	<sequence>
    		<element name="Attribute" type="tns:AttributeType"
    			minOccurs="0" maxOccurs="1">
    		</element>
    		<element name="Source" type="tns:SourceType" minOccurs="0"
    			maxOccurs="1">
    		</element>
    		<element ref="tns:LayoutItem" minOccurs="0" maxOccurs="1"></element>
    	</sequence>
    	<attribute name="id" type="string"></attribute>
    </complexType>

    <complexType name="AttributeType">
    	<sequence></sequence>
    	<attribute name="position" type="string"></attribute>
    	<attribute name="header" type="string"></attribute>
    	<attribute name="footer" type="string"></attribute>
    	<attribute name="body" type="string"></attribute>
    	<attribute name="wrap" type="string"></attribute>
    	<attribute name="grids" type="string"></attribute>
    	<attribute name="top" type="int"></attribute>
    	<attribute name="left" type="int"></attribute>
    	<attribute name="width" type="int"></attribute>
    	<attribute name="height" type="int"></attribute>
    	<attribute name="heightPercent" type="string"></attribute>
    	<attribute name="minWidth" type="int"></attribute>
    	<attribute name="maxWidth" type="int"></attribute>
    	<attribute name="minHeight" type="int"></attribute>
    	<attribute name="maxHeight" type="int"></attribute>
    	<attribute name="resize" type="string"></attribute>
    	<attribute name="gutter" type="string"></attribute>
    	<attribute name="collapse" type="string"></attribute>
    	<attribute name="scroll" type="string"></attribute>
    	<attribute name="zIndex" type="int"></attribute>
    	<attribute name="collapseSize" type="int"></attribute>
    	<attribute name="minimized" type="string"></attribute>
    	<attribute name="animate" type="string"></attribute>
    	<attribute name="proxy" type="string"></attribute>
    	<attribute name="close" type="string"></attribute>
    	<attribute name="hover" type="string"></attribute>
    </complexType>

    <complexType name="SourceType">
    	<sequence>
    		<element name="Datasource" type="string" minOccurs="0" maxOccurs="1"></element>
    	</sequence>
    	<attribute name="type" type="string"></attribute>
    	<attribute name="url" type="string"></attribute>
    	<attribute name="tabGroup" type="string"></attribute>
    	<attribute name="highlightTabId" type="string"></attribute>
    </complexType>

    <element name="LayoutItem" type="tns:LayoutItemType"></element>
</schema>

=== Lucho00Cuba/docker/symphony/shared/gui/conf/navigation/pmc_layout_SYM.xml
<?xml version="1.0" encoding="UTF-8"?>
<Layout xmlns="http://www.platform.com/gui/pmc_layout" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.platform.com/gui/pmc_layout pmc_layout.xsd">
	<LayoutItem id="applicationLayout" minWidth="400" minHeight="400">
		<LayoutUnits>
			<LayoutUnit id="center">
				<Attribute position="center" header="" gutter="0px, 0px, 0px, 0px"
					scroll="true" minWidth="100" minHeight="100" />
				<Source type="iframe"
					url="/symgui/sym/application/toApplicationList.controller" tabGroup=""
					highlightTabId="">
					<Datasource></Datasource>
				</Source>
			</LayoutUnit>
			<LayoutUnit id="bottom">
				<Attribute position="bottom" resize="true" height="370"
					header="&amp;nbsp;" gutter="8px, 0px, 0px, 0px" scroll="true"
					minWidth="100" minHeight="100" />
				<Source type="iframe" url="" tabGroup="appBottomTabGroup"
					highlightTabId="">
					<Datasource></Datasource>
				</Source>
			</LayoutUnit>
		</LayoutUnits>
	</LayoutItem>

	<LayoutItem id="symSessionLayout">
		<LayoutUnits>
			<LayoutUnit id="center">
				<Attribute position="center" header="" gutter="0px, 0px, 0px, 0px"
					scroll="true" maxHeight="500" minHeight="30" />
				<Source type="iframe" url="/symgui/sym/session/tosessions.controller">
					<Datasource></Datasource>
				</Source>
			</LayoutUnit>
			<LayoutUnit id="bottom">
				<Attribute position="bottom" resize="true" height="400"
					header="&amp;nbsp;" gutter="11px, 0px, 0px, 0px" scroll="true"
					maxHeight="500" minHeight="30" />
				<Source type="iframe" tabGroup="sessionTabGroup"
					highlightTabId="">
					<Datasource></Datasource>
				</Source>
			</LayoutUnit>
		</LayoutUnits>
	</LayoutItem>

	<!-- Symphony Tasks layout -->
	<LayoutItem id="symTasksLayout">
		<LayoutUnits>
			<LayoutUnit id="center">
				<Attribute position="center" header="" gutter="0px, 0px, 0px, 0px"
					scroll="true" maxHeight="500" minHeight="30" />
				<Source type="iframe" url="/symgui/sym/task/toTask.controller">
					<Datasource></Datasource>
				</Source>
			</LayoutUnit>
			<LayoutUnit id="bottom">
				<Attribute position="bottom" resize="true" height="400"
					header="&amp;nbsp;" gutter="11px, 0px, 0px, 0px" scroll="true"
					maxHeight="500" minHeight="30" />
				<Source type="iframe" tabGroup="symTaskTabGroup"
					highlightTabId="">
					<Datasource></Datasource>
				</Source>
			</LayoutUnit>
		</LayoutUnits>
	</LayoutItem>

	<!-- jobs without right pane -->
	<LayoutItem id="symAppProfileLayout">
		<LayoutUnits>
			<LayoutUnit id="center">
				<Attribute position="center" header="@{pmc.layout.app.profile.header}"
					gutter="0px, 0px, 0px, 0px" scroll="true" maxHeight="500"
					minHeight="30"></Attribute>
				<Source type="iframe"
					url="/platform/mixWithConsumerTree.jsp?consumerSensitivePageId=SOAM_APP_CONF_LIST&amp;moduleName=Service&amp;url=/soamgui/getAppConfInfo.controller">
					<Datasource></Datasource>
				</Source>
			</LayoutUnit>
		</LayoutUnits>
	</LayoutItem>
	<LayoutItem id="desymAppProfileLayout">
		<LayoutUnits>
			<LayoutUnit id="center">
				<Attribute position="center" header="@{pmc.layout.app.profile.header}"
					gutter="0px, 0px, 0px, 0px" scroll="true" maxHeight="500"
					minHeight="30"></Attribute>
				<Source type="iframe"
					url="/soamgui/getAppConfInfo.controller">
					<Datasource></Datasource>
				</Source>
			</LayoutUnit>
		</LayoutUnits>
	</LayoutItem>
</Layout>
