=== Lucho00Cuba/docker/symphony/shared/gui/conf/navigation/pmc_menu.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="http://www.platform.com/gui/pmc_menu" 
	xmlns:tns="http://www.platform.com/gui/pmc_menu" 
	elementFormDefault="qualified">

	<element name="Menu" type="tns:MenuType"></element>
	
	<complexType name="MenuType">
		<sequence>
			<element name="MenuItems" type="tns:MenuItemsType" minOccurs="0" maxOccurs="unbounded"></element>
		</sequence>
	</complexType>
	
	<element name="MenuItems" type="tns:MenuItemsType"></element>
	
	<complexType name="MenuItemsType">
		<sequence>
			<element name="MenuItem" type="tns:MenuItemType" minOccurs="1" maxOccurs="unbounded"></element>
		</sequence>
		<attribute name="id" type="string"></attribute>
		<attribute name="highlightMenuId" type="string"></attribute>
	</complexType>
	
	<element name="MenuItem" type="tns:MenuItemType"></element>

	<complexType name="MenuItemType">
		<sequence>
			<element ref="tns:MenuItems" minOccurs="0" maxOccurs="1"></element>
		</sequence>
		<attribute name="id" type="string"></attribute>
		<attribute name="label" type="string"></attribute>
		<attribute name="icon" type="string"></attribute>
		<attribute name="status" type="string"></attribute>
		<attribute name="url" type="string"></attribute>
		<attribute name="layoutSourceId" type="string"></attribute>
		<attribute name="tabGroup" type="string"></attribute>
		<attribute name="helpGroupId" type="string"></attribute>
		<attribute name="highlightTabId" type="string"></attribute>
		<attribute name="childUrl" type="string"></attribute>
		<attribute name="param" type="string"></attribute>
		<attribute name="aclResource" type="string"></attribute>
		<attribute name="aclPermission">
			<simpleType>
				<restriction base="int">
					<minInclusive value="1"></minInclusive>
					<maxExclusive value="7"></maxExclusive>
				</restriction>
			</simpleType>
		</attribute>
		<attribute name="disabled" type="boolean"></attribute>
	</complexType>
	
</schema>

=== Lucho00Cuba/docker/symphony/shared/gui/conf/navigation/pmc_menu_HF.xml
<?xml version="1.0" encoding="UTF-8"?>
<Menu xmlns="http://www.platform.com/gui/pmc_menu" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.platform.com/gui/pmc_menu pmc_menu.xsd">

	<MenuItems id="resourceTreeSource">
		<MenuItem id="cloud" label="@{pmc.tree.node.cloud.label}"
				icon="" status="" url="" layoutSourceId="" tabGroup=""
				highlightTabId="" aclResource="Main_host" aclPermission="1">
				<MenuItems>
					<MenuItem id="cloudHost" label="@{pmc.tree.node.cloud.hosts.label}"
						icon="" status="" url="/hfguiv6/#/cloudHosts" 
						tabGroup="" highlightTabId="" aclResource=""
						aclPermission="1" helpGroupId="resCloudHost">
					</MenuItem>
	                <MenuItem id="cloudRequest" label="@{pmc.tree.node.cloud.requests.label}"
	                    icon="" status="" url="/hfguiv6/#/requestInstances"
	                    tabGroup="" highlightTabId="" aclResource=""
	                    aclPermission="1" helpGroupId="resCloudRequest">
	                </MenuItem>
	                <MenuItem id="cloudScheduledRequests" label="@{pmc.tree.node.cloud.hf.sr}"
	                    icon="" status="" url="/hfguiv6/#/cloudrequests"
	                    tabGroup="" highlightTabId="" aclResource=""
	                    aclPermission="1" helpGroupId="resCloudRequest">
	                </MenuItem>
	                <MenuItem id="cloudRequestors" label="@{pmc.tree.node.cloud.hf.requestors}"
	                    icon="" status="" url="/hfguiv6/#/cloudRequestors"
	                    tabGroup="" highlightTabId="" aclResource=""
	                    aclPermission="1" helpGroupId="resCloudRequest">
	                </MenuItem>
	                <MenuItem id="cloudProviders" label="@{pmc.tree.node.cloud.hf.providers}"
	                    icon="" status="" url="/hfguiv6/#/cloudProviders"
	                    tabGroup="" highlightTabId="" aclResource=""
	                    aclPermission="1" helpGroupId="resCloudRequest">
	                </MenuItem>
					<MenuItem id="cloudConfiguration" label="@{pmc.tree.node.cloud.configuration.label}"
	                    icon="" status="" url="/hfguiv6/#/cloudConfiguration" 
	                    tabGroup="" highlightTabId="" aclResource=""
	                    aclPermission="1" helpGroupId="resCloudConfiguration">
	                </MenuItem>

				</MenuItems>
		</MenuItem>
	</MenuItems>
</Menu>
