=== Lucho00Cuba/docker/symphony/shared/gui/conf/navigation/pmc_navigation_tab.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="http://www.platform.com/gui/pmc_navigation_tab" 
	xmlns:tns="http://www.platform.com/gui/pmc_navigation_tab" 
	elementFormDefault="qualified">

    <element name="Navigations" type="tns:NavigationsType"></element>
    
    <complexType name="NavigationsType">
    	<sequence>
    		<element name="Navigation" type="tns:NavigationType" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <complexType name="NavigationType">
    	<sequence>
    		<element name="Handler" type="tns:HandlerType" minOccurs="0"
    			maxOccurs="1">
    		</element>
    	</sequence>
    	<attribute name="id" type="string"></attribute>
    	<attribute name="label" type="string"></attribute>
    	<attribute name="status" type="string"></attribute>
    	<attribute name="icon" type="string"></attribute>
    	<attribute name="cssClass" type="string"></attribute>
    	<attribute name="cssText" type="string"></attribute>
    	<attribute name="layoutSourceId" type="string"></attribute>
    	<attribute name="tabGroup" type="string"></attribute>
    	<attribute name="helpGroupId" type="string"></attribute>
    	<attribute name="highlightTabId" type="string"></attribute>
    	<attribute name="url" type="string"></attribute>
    	<attribute name="active" type="boolean"></attribute>
    	<attribute name="aclResource" type="string"></attribute>
    	<attribute name="aclPermission">
    		<simpleType>
    			<restriction base="int">
    				<maxInclusive value="7"></maxInclusive>
    				<minInclusive value="1"></minInclusive>
    			</restriction>
    		</simpleType>
    	</attribute>
    	<attribute name="disabled" type="boolean"></attribute>
    </complexType>

    <complexType name="HandlerType">
    	<sequence>
    		<element name="Datasource" type="string" minOccurs="0" maxOccurs="1"></element>
    		<element name="SelectNodeId" type="string" minOccurs="0" maxOccurs="1"></element>
    	</sequence>
    	<attribute name="id" type="string"></attribute>
    	<attribute name="type" type="string"></attribute>
    </complexType>
</schema>

=== Lucho00Cuba/docker/symphony/shared/gui/conf/navigation/pmc_navigation_tab.xml
<?xml version="1.0" encoding="UTF-8"?>
<Navigations xmlns="http://www.platform.com/gui/pmc_navigation_tab"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.platform.com/gui/pmc_navigation_tab pmc_navigation_tab.xsd">

	<Navigation id="resources" label="@{pmc.navigation.tab.resources.label}"
		status="display" icon="images/tabicons/pcmcluster.gif" layoutSourceId=""
		tabGroup="" highlightTabId="" url="" aclResource="" aclPermission="1"
		helpGroupId="helpresources">
		<Handler id="resourceTrigger" type="menu">
			<Datasource>resourceTreeSource</Datasource>
			<SelectNodeId>hostListIcon</SelectNodeId>
		</Handler>
	</Navigation>

	<Navigation id="system" label="@{pmc.navigation.tab.settings.label}"
		status="display" icon="images/tabicons/pmcusers.gif" aclResource=""
		aclPermission="1" helpGroupId="helpsystem">
		<Handler id="systemTrigger" type="menu">
			<Datasource>systemTreeSource</Datasource>
			<SelectNodeId>entitlement</SelectNodeId>
		</Handler>
	</Navigation>

	<Navigation id="eventAndReport" label="@{pmc.navigation.tab.reportLog.label}"
		status="display" icon="images/tabicons/pmcusers.gif" layoutSourceId=""
		tabGroup="" highlightTabId="" url="" aclResource="" aclPermission="1"
		helpGroupId="helpeventandreport">
		<Handler id="eventAndReportTrigger" type="menu">
			<Datasource>eventAndReportTreeSource</Datasource>
			<SelectNodeId>standardReport</SelectNodeId>
		</Handler>
	</Navigation>

	<Navigation id="eventAndReportExpress" label="@{pmc.navigation.tab.Logs.label}"
		status="display" icon="images/tabicons/pmcusers.gif" layoutSourceId=""
		tabGroup="" highlightTabId="" url="" aclResource="" aclPermission="1"
		helpGroupId="helpeventandreport">
		<Handler id="eventAndReportTrigger" type="menu">
			<Datasource>eventAndReportTreeSource</Datasource>
			<SelectNodeId>standardReport</SelectNodeId>
		</Handler>
	</Navigation>

	<Navigation id="harvesting" label="@{pmc.navigation.tab.harvesting.label}"
		status="display" icon="images/tabicons/pmcusers.gif" aclResource=""
		aclPermission="1" helpGroupId="helpharvesting">
		<Handler id="harvestTrigger" type="menu">
			<Datasource>harvesting</Datasource>
			<SelectNodeId>harvestingHost</SelectNodeId>
		</Handler>
	</Navigation>
	
	<Navigation id="integration" label="@{pmc.navigation.tab.integration.label}"
		status="display" icon="images/tabicons/pmcusers.gif" aclResource=""
		aclPermission="1" helpGroupId="helpintegration">
		<Handler id="integrationTrigger" type="menu">
			<Datasource>integration</Datasource>
			<SelectNodeId>yarn</SelectNodeId>
		</Handler>
	</Navigation>
		
	<Navigation id="dashboard" label="@{pmc.navigation.tab.dashboard.label}"
		status="display" icon="images/tabicons/pmcusers.gif" aclResource=""
		aclPermission="1" helpGroupId="" cssClass="dock">
		<Handler id="dashboardTrigger" type="menu">
			<Datasource>symDashboardMenu</Datasource>
			<SelectNodeId>symDashboard</SelectNodeId>
		</Handler>
	</Navigation>
	
</Navigations>

=== Lucho00Cuba/docker/symphony/shared/gui/conf/asp_portal/report/navigation/pmc_navigation_tab.xml
<?xml version="1.0" encoding="UTF-8"?>
<Navigations xmlns="http://www.platform.com/gui/pmc_navigation_tab"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.platform.com/gui/pmc_navigation_tab pmc_navigation_tab.xsd">
	
	<Navigation id="jobs" label="@{pmc.navigation.tab.jobs.label}" status="display" icon="images/tabicons/workloadMgmt.gif"
		layoutSourceId="" tabGroup="" highlightTabId="" url="">
		<Handler id="testTrigger" type="tree">
			<Datasource>jobsTreeSource</Datasource>
			<SelectNodeId>Jobs</SelectNodeId>
		</Handler>
	</Navigation>
	
	<Navigation id="resource" label="@{pmc.navigation.tab.resources.label}" status="display" icon="images/tabicons/pcmcluster.gif"
		layoutSourceId="" tabGroup="" highlightTabId="" url="">
		<Handler id="resourceTrigger" type="tree">
			<Datasource>resourceTreeSource</Datasource>
			<SelectNodeId></SelectNodeId>
		</Handler>
	</Navigation>
	
	<Navigation id="settings" label="@{pmc.navigation.tab.settings.label}" status="display" icon="images/tabicons/pmcusers.gif" >
		<Handler id="configurationsTrigger" type="tree">
			<Datasource>settingsTreeSource</Datasource>
			<SelectNodeId>userGroups</SelectNodeId>
		</Handler>
	</Navigation>
	
	<Navigation id="reports" label="@{pmc.navigation.tab.perfreports.label}" status="display" icon="images/tabicons/report3d.gif"
		layoutSourceId="" tabGroup="" highlightTabId="" url="/report/reportListingAction.controller?folder=ResourceUsage&amp;reportType=2" aclResource="All Reports" aclPermission="1">
		<Handler id="reportsTrigger" type="tree">
			<Datasource>reportsTreeSource</Datasource>
			<SelectNodeId></SelectNodeId>
		</Handler>
	</Navigation>

	<Navigation id="reportInstance" label="@{pmc.navigation.tab.perfreports.instance.label}" status="display" icon="images/tabicons/report3d.gif"
                layoutSourceId="" tabGroup="" highlightTabId="" url="/report/reportInstanceManageAction.controller?directory=<reportInstanceDirectory>&amp;reportType=2&amp;dispatch=reportInstanceLIST" aclResource="All Reports" aclPermission="1">
                <Handler id="reportInstanceTrigger" type="tree">
                        <Datasource>reportInstanceTreeSource</Datasource>
                        <SelectNodeId></SelectNodeId>
                </Handler>
        </Navigation>
</Navigations>
