=== Lucho00Cuba/docker/symphony/shared/gui/conf/pmcconf/pmc_conf.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : pmc_conf.dtd
    Created on : August 4, 2006, 11:31 AM
    Author     : Whu
    Description:
        Save UI architecture configurations include dashboard position and configurable mainConsole Tab.

    TODO define vocabulary identification data
    PUBLIC ID  : -//vendor//vocabulary//EN
    SYSTEM ID  : http://server/path/pmc_conf.dtd
-->

<!-- TODO define your own vocabulary/syntax. Example follows:  -->
<!ELEMENT ParamConfs (MainConsole?,Dashboard?,Configuration?)>
<!ELEMENT MainConsole (Module*)> 
<!ATTLIST MainConsole TabStyle CDATA "top" >
<!ATTLIST Module Name CDATA #REQUIRED>
<!ATTLIST Module URL CDATA #REQUIRED>
<!ATTLIST Module UserAclName CDATA "">
<!ATTLIST Module LogoutURL CDATA "">
<!ATTLIST Module HasConsumerTree CDATA "no">
<!ATTLIST Module OnlineHelpURL CDATA "/platform/help/no_help.html">
<!ATTLIST Module IconStyle CDATA "moduleTab-0">
<!ATTLIST Module HasDefault CDATA "no">
<!ATTLIST Module TabIndex CDATA "0">
<!ELEMENT Module (ModuleItem*)>
<!ELEMENT ModuleItem EMPTY>
<!ATTLIST ModuleItem Name CDATA #REQUIRED>
<!ATTLIST ModuleItem URL CDATA #REQUIRED>
<!ATTLIST ModuleItem UserAclName CDATA "">
<!ATTLIST ModuleItem HasConsumerTree CDATA "no">
<!ATTLIST ModuleItem HasDefault CDATA "no">
<!ATTLIST ModuleItem LogoutURL CDATA "">
<!ATTLIST ModuleItem OnlineHelpURL CDATA "/platform/help/no_help.html">
<!ATTLIST ModuleItem IconStyle CDATA "moduleTab-0">
<!ATTLIST ModuleItem TabIndex CDATA "0">
<!ELEMENT Dashboard (Layout*)> 
<!ELEMENT Layout EMPTY>
<!ATTLIST Layout  Name CDATA #REQUIRED>
<!ATTLIST Layout  URL CDATA #REQUIRED>
<!ATTLIST Layout  Module CDATA #REQUIRED>
<!ATTLIST Layout  HasTitle CDATA "yes">
<!ATTLIST Layout  HasPerformMin CDATA "no">
<!ATTLIST Layout  HasResize CDATA "yes">
<!ATTLIST Layout  HasMove CDATA "yes">
<!ATTLIST Layout  HasAutoRefresh CDATA "yes">
<!ATTLIST Layout  HasDefaultMin CDATA "yes">
<!ATTLIST Layout  Width CDATA "440">
<!ATTLIST Layout  Height CDATA "500">
<!ATTLIST Layout  Top CDATA "0">
<!ATTLIST Layout  Left CDATA "0">
<!ATTLIST Layout  MarginHeight CDATA "0">
<!ATTLIST Layout  MarginWidth CDATA "0">
<!ATTLIST Layout  FrameBorder CDATA "1">
<!ATTLIST Layout  Scrolling CDATA "auto">
<!ELEMENT Configuration (Parameter*)>
<!ELEMENT Parameter (Name,Value)*>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Value (#PCDATA)>

=== Lucho00Cuba/docker/symphony/shared/gui/conf/pmcconf/pmc_conf_is.xml
<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE ParamConfs SYSTEM "pmc_conf.dtd"> 
<ParamConfs> 
	<MainConsole TabStyle="top">
		<Module Name="HARVESTING" UserAclName="Main_HARVESTING" URL="/platform/getHarvestingHostInfo.controller" OnlineHelpURL="/doc/help/scav_hosts_list_understanding.html" IconStyle="moduleTab-9">
			<ModuleItem Name="VM Resources" UserAclName="IS_VMCluster" URL="/isgui/getResourceView.controller" HasConsumerTree="no"/>
		</Module>
	</MainConsole>
	<Configuration>
		<Parameter>
			<!--  VM Cluster list refresh interval, unit:second,it should be between 10 and 900, belong to IS -->
			<Name>VMClusterInterval</Name>
			<Value>30</Value>
		</Parameter>
		<Parameter>
			 <!--  timeout for perform action with backend, unit:second,it should be bigger than 1 , belong to IS -->
			 <Name>ISPerformTimeOut</Name>
			 <Value>300</Value>
		 </Parameter>
		<Parameter>
			 <!--  timeout for query from backend, unit:second,it should be bigger than 1 , belong to IS-->
			 <Name>ISQueryTimeOut</Name>
			 <Value>60</Value>
		 </Parameter>
		 <Parameter>
			 <!--  retry limit for query from backend, unit:account time,it should be bigger than 0 , belong to IS-->
			 <Name>ISQueryRetryLimit</Name>
			 <Value>3</Value>
		 </Parameter>
	</Configuration>
</ParamConfs>
