=== Lucho00Cuba/docker/symphony/shared/gui/conf/userconf/UserConf.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : UserConf.dtd
    Created on : September 21, 2005, 12:31 PM
    Author     : jliu
    Description:
        Save user configurations include view preference, session expire time.

    TODO define vocabulary identification data
    PUBLIC ID  : -//vendor//vocabulary//EN
    SYSTEM ID  : http://server/path/UserConf.dtd
-->

<!-- TODO define your own vocabulary/syntax. Example follows:  -->
<!ELEMENT UserConfs (ViewPreference*,FilterSetting*,SiteMapSetting?,Configuration?,SessionConf?,TaskConf?)>
<!ELEMENT ViewPreference EMPTY>
<!ATTLIST ViewPreference Type CDATA #REQUIRED>
<!ATTLIST ViewPreference MaxPageSize CDATA "">
<!ATTLIST ViewPreference EnableAutoRefresh CDATA "">
<!ATTLIST ViewPreference RefreshTime CDATA "">
<!ATTLIST ViewPreference SelectedColumns CDATA #REQUIRED>
<!ATTLIST ViewPreference UnselectedColumns CDATA #REQUIRED>
<!ATTLIST ViewPreference SortBy CDATA "">
<!ATTLIST ViewPreference SortDir CDATA "">
<!ATTLIST ViewPreference TitleName CDATA "">
<!ATTLIST ViewPreference SiteMapType CDATA "">
<!ELEMENT SessionConf EMPTY>
<!ATTLIST SessionConf ExpireTime CDATA "">
<!ELEMENT TaskConf EMPTY>
<!ATTLIST TaskConf Cap CDATA "">
<!ELEMENT Configuration (Parameter*)>
<!ELEMENT Parameter (Name,Value)*>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Value (#PCDATA)>
<!ELEMENT FilterSetting EMPTY>
<!ATTLIST FilterSetting Type CDATA #REQUIRED>
<!ATTLIST FilterSetting Name CDATA #REQUIRED>
<!ATTLIST FilterSetting Value CDATA #REQUIRED>
<!ELEMENT SiteMapSetting EMPTY>
<!ATTLIST SiteMapSetting Type CDATA #REQUIRED>
<!ATTLIST SiteMapSetting Value CDATA #REQUIRED>

=== Lucho00Cuba/docker/symphony/shared/gui/conf/userconf/userconf.soam.xml
<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE UserConfs SYSTEM "UserConf.dtd"> 
<UserConfs> 

<ViewPreference 
	Type="application" 
	RefreshTime="60" 
	SelectedColumns="appName,appState,sessionSummary,openSessions:N,suspSessions:N,closeSessions:N,abortedSessions:N,ssmHost,ssmPid:N,hostPidPairs,blockHostCount:N" 
	UnselectedColumns="consumer,appRunningTasks:N,appPendingTasks:N,appDoneTasks:N,appCancelTasks:N,appErrorTasks:N,resourceSummary,ssmStartTime,lastSessionAbortTime,lastTaskErrorTime,allocatedSlotsTask:N,budgetedSlotsTask:N,staticShareReserveTask:N,allocatedSlotsSystem:N,budgetedSlotsSystem:N,appTotalTasks:N,ssmVersion,enablePrestart,configuredPreload:N,enableStandby,standbyServiceThreshold:N,demanded:N,allocated:N,releasing:N,unallocatedStandby:N,preemptionCriteria,enableSelectiveReclaim,preemptionScope,policy,schedulingAffinity" 
	SortBy="appName" 
	SortDir="ascending" />
<ViewPreference 
	Type="appsum1" 
	SelectedColumns="appName,appRunningTasks:N,appPendingTasks:N,appDoneTasks:N,appErrorTasks:N,appCancelTasks:N,allocatedSlotsTask:N,budgetedSlotsTask:N,blockHostCount:N" 
	UnselectedColumns="appState,ssmHost,ssmPid:N,consumer,openSessions:N,suspSessions:N,closeSessions:N,abortedSessions:N,sessionSummary,resourceSummary,ssmStartTime,lastSessionAbortTime,lastTaskErrorTime,staticShareReserveTask:N,allocatedSlotsSystem:N,budgetedSlotsSystem:N,appTotalTasks:N,ssmVersion,hostPidPairs,enablePrestart,configuredPreload:N,enableStandby,standbyServiceThreshold:N,demanded:N,allocated:N,releasing:N,unallocatedStandby:N,preemptionCriteria,enableSelectiveReclaim,preemptionScope,policy,schedulingAffinity,deserved:N,assigned:N" 
	TitleName="Tasks" />
<ViewPreference 
	Type="appsum2" 
	SelectedColumns="appName,suspSessions:N,abortedSessions:N,openSessions:N,closeSessions:N,blockHostCount:N" 
	UnselectedColumns="appState,ssmHost,ssmPid:N,consumer,appRunningTasks:N,appPendingTasks:N,appDoneTasks:N,appErrorTasks:N,appCancelTasks:N,sessionSummary,resourceSummary,ssmStartTime,lastSessionAbortTime,lastTaskErrorTime,allocatedSlotsTask:N,budgetedSlotsTask:N,staticShareReserveTask:N,allocatedSlotsSystem:N,budgetedSlotsSystem:N,appTotalTasks:N,ssmVersion,hostPidPairs,enablePrestart,configuredPreload:N,enableStandby,standbyServiceThreshold:N,demanded:N,allocated:N,releasing:N,unallocatedStandby:N,preemptionCriteria,enableSelectiveReclaim,preemptionScope,policy,schedulingAffinity,deserved:N,assigned:N" 
	TitleName="Sessions" />
<ViewPreference 
	Type="appConf" 
	RefreshTime="60" 
	SelectedColumns="appName,appState,appPackages,registeredConsumer,ssmConfiguredVersion" 
	UnselectedColumns="" 
	SortBy="appName" 
	SortDir="ascending" />

<ViewPreference 
	Type="session" 
	RefreshTime="60" 
	MaxPageSize="12" 
	SelectedColumns="sessionId:N,state,priority:N,taskSummary,runTasks:N,pendTasks:N,doneTasks:N,errTasks:N,cancelTasks:N,userName,numInstances:N,totalTasks:N,hostPidPairs,commonDataUpdates:N" 
	UnselectedColumns="sessionName,sessionTag,createTime,endTime,service,type,reason,consumer,retryLimit:N,failIfTaskFail,recoverable,persistSessionHistory,persistTaskHistory,lastTaskErrorTime,appName,sessionRetryLimit:N,commonDataSize:N,sessionUpdateFailures,totalNetworkSizeCduUpdates:N,rawCommonDataSize:N,compressionEnabled,compressionThreshold:N,compressionApplied,directDataTransferEnabled,preemptive,clientHostName,clientOSUserName,clientVersion,clientIPAddress,serviceToSlotRatio,resourceGroupFilter,demanded:N,deserved:N,assigned:N,preemptionRank:N,preference,defaultResourceAttributeValue:N,tasksInterruptedByPreempt:N,runTimeInterruptedByPreempt,tasksInterruptedByReclaim:N,runTimeInterruptedByReclaim,minimumServices:N,maximumServices:N" 
	TitleName="Session View" />
<ViewPreference 
	Type="task"  
	RefreshTime="60" 
	MaxPageSize="12" 
	SelectedColumns="taskId:N,state,taskPriority:N,submitTime,startTime,endTime,rerunCount:N,runHost,error,commonDataUpdates:N" 
	UnselectedColumns="taskTag,siPid:N,inputMsgSize:N,outputMsgSize:N,reason,compressionEnabled,compressionThreshold:N,rawInputSize:N,rawOutputSize:N,compressionAppliedInput,compressionAppliedOutput,directDataTransferEnabled,preference" 
	TitleName="Task View" />
<ViewPreference 
	Type="blockhost"  
	MaxPageSize="12" 
	SelectedColumns="hostname,allocationID:N" 
	UnselectedColumns="" 
	SortBy="hostname" 
	SortDir="ascending" 
	TitleName="BlockList View" />
<ViewPreference 
	Type="soamResource"  
	MaxPageSize="12" 
	SelectedColumns="hostName,slots:N,sessionId:N,resGroup,svc2SlotRatio,state" 
	UnselectedColumns="" 
	SortBy="hostName" 
	SortDir="ascending" 
	TitleName="Resource View" />

<ViewPreference 
	Type="appLog" 
	MaxPageSize="10" 
	SelectedColumns="speclogname,date,hosts,size:N" 
	UnselectedColumns="" 
	SortBy="speclogname" 
	SortDir="descending" />
<ViewPreference 
	Type="taskLog" 
	MaxPageSize="10" 
	SelectedColumns="speclogname,date,hosts,size:N" 
	UnselectedColumns="" 
	SortBy="speclogname" 
	SortDir="descending" />

<FilterSetting  Type="session" Name="SessionState" Value="Any" />
<FilterSetting  Type="session" Name="SessionUser" Value="Any" />
<FilterSetting  Type="task" Name="TaskState" Value="Running" />

</UserConfs>
