=== Lucho00Cuba/docker/symphony/shared/gui/conf/asp_portal/report/table_maintenance/table_maintenance.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="TableMaintenance">
		<xs:annotation>
			<xs:documentation>The root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Descriptions">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Name" type="xs:string"/>
							<xs:element name="Summary" type="xs:string" minOccurs="0"/>
							<xs:element name="Folder" type="xs:string" minOccurs="0"/>
							<xs:element name="Discription" type="xs:string" minOccurs="0"/>
							<xs:element name="DisplayName" type="xs:string" minOccurs="0"/>
							<xs:element name="Category" type="xs:string" minOccurs="0"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Insert" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Parameters">
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="Parameter" minOccurs="0" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Queries">
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="Query" minOccurs="0" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Delete" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Parameters">
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="Parameter" minOccurs="0" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Queries">
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="Query" minOccurs="0" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Update" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Parameters">
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="Parameter" minOccurs="0" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Queries">
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="Query" minOccurs="0" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Select" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Parameters">
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="Parameter" minOccurs="0" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Queries">
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="Query" minOccurs="0" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Outputs">
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="Column" minOccurs="0" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Variables" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="Variable" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Sources" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="Source" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Variable">
		<xs:annotation>
			<xs:documentation>The definition of variable of the report</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Format" minOccurs="0">
					<xs:complexType>
						<xs:attribute name="Plug-in" type="xs:string" use="required"/>
						<xs:anyAttribute processContents="skip"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="Name" type="xs:string" use="required"/>
			<xs:attribute name="Target" type="xs:string" use="required"/>
			<xs:attribute name="Source" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="Default" type="xs:string"/>
			<xs:attribute name="Function">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="Source">
		<xs:annotation>
			<xs:documentation>The definition of source of the report</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Parameter" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType mixed="true">
						<xs:choice>
							<xs:any processContents="skip" minOccurs="0"/>
						</xs:choice>
						<xs:attribute name="Name" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="Name" type="xs:string" use="required"/>
			<xs:attribute name="Plug-in" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Query">
		<xs:annotation>
			<xs:documentation>One named query statement. </xs:documentation>
		</xs:annotation>
		<xs:complexType mixed="true">
			<xs:sequence>
				<xs:element name="SQL" type="xs:string">
					<xs:annotation>
						<xs:documentation>The query sql statement. This query can include some var through %%%VarA%%% etc.</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="DBType" use="required">
				<xs:annotation>
					<xs:documentation>The name of query statement. E.g. it can named as Oracle9i,Oracle10g,MySQL etc.</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="ORACLE"/>
						<xs:enumeration value="DERBY"/>
						<xs:enumeration value="MYSQL"/>
						<xs:enumeration value="STANDARD"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:anyAttribute processContents="skip"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Parameter">
		<xs:annotation>
			<xs:documentation>One Parameter. There are three kind of type.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Attributes" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Attribute" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>The attribute for display custom tags. E.g. For CheckList custom tag, it needs a attribute to display which named size, so you can define an attribute name="size" value="10"</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:attribute name="Name" type="xs:string" use="required">
										<xs:annotation>
											<xs:documentation>The name of attribute</xs:documentation>
										</xs:annotation>
									</xs:attribute>
									<xs:attribute name="Value" type="xs:string" use="required">
										<xs:annotation>
											<xs:documentation>The value of attribute</xs:documentation>
										</xs:annotation>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:choice minOccurs="0">
					<xs:element name="ListValue" minOccurs="0">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="Item" maxOccurs="unbounded">
									<xs:annotation>
										<xs:documentation>For dropdownlist or checklist</xs:documentation>
									</xs:annotation>
									<xs:complexType>
										<xs:attribute name="Value" type="xs:string" use="required"/>
										<xs:attribute name="Label" type="xs:string"/>
									</xs:complexType>
								</xs:element>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="VarValue" minOccurs="0">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="Field" maxOccurs="unbounded">
									<xs:complexType>
										<xs:attribute name="Type" type="xs:string" use="required">
											<xs:annotation>
												<xs:documentation>The type can be value and label, the value means the key of values, the label means the display value of values.</xs:documentation>
											</xs:annotation>
										</xs:attribute>
										<xs:attribute name="Column" type="xs:string" use="required">
											<xs:annotation>
												<xs:documentation>This attribute will map the column name from select sql statement</xs:documentation>
											</xs:annotation>
										</xs:attribute>
									</xs:complexType>
								</xs:element>
							</xs:sequence>
							<xs:attribute name="Name" type="xs:string"/>
						</xs:complexType>
					</xs:element>
				</xs:choice>
			</xs:sequence>
			<xs:attribute name="Name" use="required">
				<xs:annotation>
					<xs:documentation>The name of parameter</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="Type" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>The type of Parameter. This Type will drive the custom tag type.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="Label" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Column">
		<xs:annotation>
			<xs:documentation>Column name in dataset</xs:documentation>
		</xs:annotation>
		<xs:complexType mixed="false">
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="Name" type="xs:string" use="optional"/>
					<xs:attribute name="Label" type="xs:string" use="optional"/>
					<xs:attribute name="Type" use="optional">
						<xs:simpleType>
							<xs:restriction base="xs:string"/>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="Display"/>
					<xs:attribute name="ContentStyle"/>
					<xs:attribute name="HearderStyle"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Lucho00Cuba/docker/symphony/shared/gui/conf/asp_portal/report/table_maintenance/WI_LICENSERATE.xml
<?xml version="1.0" encoding="UTF-8"?>
<TableMaintenance xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="table_maintenance.xsd">
	<Descriptions>
		<Name>License Accounting Rate Table Maintenance</Name>
		<Summary>许可证费率表的维护, 包括插入数据, 删除数据, 修改数据</Summary>
		<Folder>TableMaintenance</Folder>
		<Discription>许可证费率表的维护</Discription>
		<DisplayName>许可证费率表的维护</DisplayName>
		<Category>计费表的维护</Category>
	</Descriptions>
	<Insert>
		<Parameters>
			<Parameter Name="LIC_FEATURE_NAME" Type="DROPDOWNLIST" Label="许可证">
				<VarValue Name="${LIC_FEATURE_MAP}">
					<Field Type="Value" Column="LIC_FEATURE_CODE" />
					<Field Type="Label" Column="LIC_FEATURE_NAME" />
				</VarValue>
			</Parameter>
			<Parameter Name="LIC_VENDOR_NAME" Type="DROPDOWNLIST" Label="许可证生产商">
				<VarValue Name="${LIC_VENDOR_MAP}">
					<Field Type="Value" Column="LIC_VENDOR_CODE" />
					<Field Type="Label" Column="LIC_VENDOR_NAME" />
				</VarValue>
			</Parameter>
			<Parameter Name="BUSINESS_HOUR_CODE" Type="DROPDOWNLIST" Label="商业时间">
				<ListValue>
     					<Item Value="1" Label="工作日" />
     					<Item Value="0" Label="非工作日" />
    				</ListValue>
			</Parameter>
			<Parameter Name="LIC_RATE" Type="TEXT" Label="许可证费率(/小时)" />
		</Parameters>
		<Queries>
			<Query DBType="ORACLE">
				<SQL>
				<![CDATA[
INSERT INTO LICENSE_RATE(LIC_VENDOR_NAME, LIC_FEATURE_NAME, BUSINESS_HOUR_CODE, LIC_RATE) 
       VALUES('${LIC_VENDOR_NAME}', '${LIC_FEATURE_NAME}', ${BUSINESS_HOUR_CODE}, ${LIC_RATE})
 ]]>
				</SQL>
			</Query>
		</Queries>
	</Insert>
	<Delete>
		<Parameters>
		</Parameters>
		<Queries>
			<Query DBType="ORACLE">
				<SQL>
				<![CDATA[
DELETE LICENSE_RATE 
WHERE ROWID='${ROW_ID}'
 ]]>
				</SQL>
			</Query>
		</Queries>
	</Delete>
	<Update>
		<Parameters>
			<Parameter Name="LIC_FEATURE_NAME" Type="DROPDOWNLIST" Label="许可证功能">
				<VarValue Name="${LIC_FEATURE_MAP}">
					<Field Type="Value" Column="LIC_FEATURE_CODE" />
					<Field Type="Label" Column="LIC_FEATURE_NAME" />
				</VarValue>
			</Parameter>
			<Parameter Name="LIC_VENDOR_NAME" Type="DROPDOWNLIST" Label="许可证生产商">
				<VarValue Name="${LIC_VENDOR_MAP}">
					<Field Type="Value" Column="LIC_VENDOR_CODE" />
					<Field Type="Label" Column="LIC_VENDOR_NAME" />
				</VarValue>
			</Parameter>
			<Parameter Name="BUSINESS_HOUR_CODE" Type="DROPDOWNLIST" Label="商业时间">
				<ListValue>
     					<Item Value="1" Label="工作日" />
     					<Item Value="0" Label="非工作日" />
    				</ListValue>
			</Parameter>
			<Parameter Name="LIC_RATE" Type="TEXT" Label="许可证费率(/小时)" />
			
		</Parameters>
		<Queries>
			<Query DBType="ORACLE">
				<SQL>
				<![CDATA[
UPDATE LICENSE_RATE 
SET 
  LIC_RATE = ${LIC_RATE}, 
  LIC_FEATURE_NAME = '${LIC_FEATURE_NAME}',
  LIC_VENDOR_NAME = '${LIC_VENDOR_NAME}',
  BUSINESS_HOUR_CODE = ${BUSINESS_HOUR_CODE}
WHERE ROWID='${ROW_ID}'
 ]]>
				</SQL>
			</Query>
		</Queries>
	</Update>

	<Select>
		<Parameters>
			<Parameter Name="LIC_FEATURE_NAME" Type="DROPDOWNLIST" Label="许可证功能">
				<VarValue Name="${LIC_FEATURE_MAP}">
					<Field Type="Value" Column="LIC_FEATURE_CODE" />
					<Field Type="Label" Column="LIC_FEATURE_NAME" />
				</VarValue>
			</Parameter>
			<Parameter Name="LIC_VENDOR_NAME" Type="DROPDOWNLIST" Label="许可证生产商">
				<VarValue Name="${LIC_VENDOR_MAP}">
					<Field Type="Value" Column="LIC_VENDOR_CODE" />
					<Field Type="Label" Column="LIC_VENDOR_NAME" />
				</VarValue>
			</Parameter>
			<Parameter Name="BUSINESS_HOUR_CODE" Type="DROPDOWNLIST" Label="商业时间">
				<ListValue>
     					<Item Value="1" Label="工作日" />
     					<Item Value="0" Label="非工作日" />
    				</ListValue>
			</Parameter>
			<Parameter Name="LIC_RATE" Type="TEXT" Label="许可证费率(/小时)" />
		</Parameters>
		<Queries>
			<Query DBType="ORACLE">
				<SQL>
					<![CDATA[
SELECT ROWIDTOCHAR(LR.ROWID) AS ROW_ID, LR.*
FROM  LICENSE_RATE LR
 ]]>
				</SQL>
			</Query>
		</Queries>
		<Outputs>
			<Column Name="LIC_VENDOR_NAME" Label="许可证生产商" Type="INT" Display="YES" ContentStyle="NORMAL" HearderStyle="BOLD" />
			<Column Name="LIC_FEATURE_NAME" Label="许可证" Type="INT" Display="YES" ContentStyle="NORMAL" HearderStyle="BOLD" />
			<Column Name="BUSINESS_HOUR_CODE" Label="商业时间" Type="INT" Display="YES" ContentStyle="NORMAL" HearderStyle="BOLD" />
			<Column Name="LIC_RATE" Label="许可证费率(/小时)" Type="INT" Display="YES" ContentStyle="NORMAL" HearderStyle="BOLD" />
			<Column Name="ROW_ID" Label="行号" Type="STRING" Display="NO" />
		</Outputs>
	</Select>

	<Variables>		
		<Variable Name="LIC_VENDOR_NAME" Target="LIC_VENDOR_NAME" Source="REQUEST" />
		<Variable Name="LIC_FEATURE_NAME" Target="LIC_FEATURE_NAME" Source="REQUEST" />
		<Variable Name="BUSINESS_HOUR_CODE" Target="BUSINESS_HOUR_CODE" Source="REQUEST" />
		<Variable Name="LIC_RATE" Target="LIC_RATE" Source="REQUEST" />	
			
		<Variable Name="ROW_ID" Target="ROW_ID" Source="REQUEST" />
		
		<Variable Name="LIC_FEATURE_MAP" Target="" Source="LIC_FEATURE_SOURCE" />
		<Variable Name="LIC_VENDOR_MAP" Target="" Source="LIC_VENDOR_SOURCE" />
		
	</Variables>
	<Sources>
		<Source Name="REQUEST" Plug-in="com.platform.perf.report.config.var.source.RequestVariableSource" />
		<Source Name="LIC_FEATURE_SOURCE" Plug-in="com.platform.perf.report.config.var.source.SQLVaraibleSource">
			<Parameter Name="QUERIES">
				<Queries>
					<Query DBType="STANDARD">
						<SQL>
							<![CDATA[
							SELECT DISTINCT LIC_FEATURE_NAME AS LIC_FEATURE_CODE, LIC_FEATURE_NAME FROM LICENSE_ACCOUNTING
						]]>
						</SQL>
					</Query>
				</Queries>
			</Parameter>
		</Source>
		<Source Name="LIC_VENDOR_SOURCE" Plug-in="com.platform.perf.report.config.var.source.SQLVaraibleSource">
			<Parameter Name="QUERIES">
				<Queries>
					<Query DBType="STANDARD">
						<SQL>
							<![CDATA[
							SELECT DISTINCT LIC_VENDOR_NAME AS LIC_VENDOR_CODE, LIC_VENDOR_NAME FROM LICENSE_ACCOUNTING
						]]>
						</SQL>
					</Query>
				</Queries>
			</Parameter>
		</Source>
		
	</Sources>
</TableMaintenance>

=== Lucho00Cuba/docker/symphony/shared/gui/conf/asp_portal/report/table_maintenance/WI_QUEUERATE.xml
<?xml version="1.0" encoding="UTF-8"?>
<TableMaintenance xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="table_maintenance.xsd">
	<Descriptions>
		<Name>Queue Accounting Rate Table Maintenance</Name>
		<Summary>作业队列费率表的维护</Summary>
		<Folder>TableMaintenance</Folder>
		<Discription>作业队列费率表的维护</Discription>
		<DisplayName>作业队列费率表的维护</DisplayName>
		<Category>计费表的维护</Category>
	</Descriptions>
	<Insert>
		<Parameters>
			<Parameter Name="QUEUE_NAME" Type="DROPDOWNLIST" Label="队列">
				<VarValue Name="${QUEUE_MAP}">
					<Field Type="Value" Column="QUEUE_CODE" />
					<Field Type="Label" Column="QUEUE_NAME" />
				</VarValue>
			</Parameter>
			<Parameter Name="BUSINESS_HOUR_CODE" Type="DROPDOWNLIST" Label="时间">
				<ListValue>
     				<Item Value="1" Label="工作日" />
     				<Item Value="0" Label="非工作日" />
    			</ListValue>
			</Parameter>
			<Parameter Name="QUEUE_RATE" Type="TEXT" Label="费率(元/小时)">	
			</Parameter>
		</Parameters>
		<Queries>
			<Query DBType="ORACLE">
				<SQL>
				<![CDATA[
INSERT INTO 
       QUEUE_RATE(QUEUE_NAME, BUSINESS_HOUR_CODE, QUEUE_RATE) 
       VALUES('${QUEUE_NAME}', ${BUSINESS_HOUR_CODE}, ${QUEUE_RATE})
 ]]>
				</SQL>
			</Query>
		</Queries>
	</Insert>
	<Delete>
		<Parameters>
		</Parameters>
		<Queries>
			<Query DBType="ORACLE">
				<SQL>
				<![CDATA[
DELETE QUEUE_RATE 
WHERE ROWID='${ROW_ID}'
 ]]>
				</SQL>
			</Query>
		</Queries>
	</Delete>
	<Update>
		<Parameters>
			<Parameter Name="QUEUE_NAME" Type="DROPDOWNLIST" Label="队列">
				<VarValue Name="${QUEUE_MAP}">
					<Field Type="Value" Column="QUEUE_CODE" />
					<Field Type="Label" Column="QUEUE_NAME" />
				</VarValue>
			</Parameter>
			<Parameter Name="BUSINESS_HOUR_CODE" Type="DROPDOWNLIST" Label="时间">
				<ListValue>
     				<Item Value="1" Label="工作日" />
     				<Item Value="0" Label="非工作日" />
    			</ListValue>
			</Parameter>
			<Parameter Name="QUEUE_RATE" Type="TEXT" Label="费率(元/小时)">	
			</Parameter>
		</Parameters>
		<Queries>
			<Query DBType="ORACLE">
				<SQL>
				<![CDATA[
UPDATE QUEUE_RATE 
SET 
  QUEUE_RATE = ${QUEUE_RATE},
  QUEUE_NAME = '${QUEUE_NAME}',
  BUSINESS_HOUR_CODE = ${BUSINESS_HOUR_CODE}
WHERE ROWID='${ROW_ID}'
 ]]>
				</SQL>
			</Query>
		</Queries>
	</Update>
	<Select>
		<Parameters>
			<Parameter Name="QUEUE_NAME" Type="DROPDOWNLIST" Label="队列">
				<VarValue Name="${QUEUE_MAP}">
					<Field Type="Value" Column="QUEUE_CODE" />
					<Field Type="Label" Column="QUEUE_NAME" />
				</VarValue>
			</Parameter>
			<Parameter Name="BUSINESS_HOUR_CODE" Type="DROPDOWNLIST" Label="时间">
				<ListValue>
     					<Item Value="1" Label="工作日" />
     					<Item Value="0" Label="非工作日" />
    				</ListValue>
			</Parameter>
			<Parameter Name="QUEUE_RATE" Type="TEXT" Label="费率(元/小时)">	
			</Parameter>
		</Parameters>
		<Queries>
			<Query DBType="ORACLE">
				<SQL>
					<![CDATA[
SELECT ROWIDTOCHAR(QR.ROWID) AS ROW_ID, QR.*
FROM QUEUE_RATE QR
 ]]>
				</SQL>
			</Query>
		</Queries>
		<Outputs>
			<Column Name="QUEUE_NAME" Label="队列" Type="INT" Display="YES" ContentStyle="NORMAL" HearderStyle="BOLD" />
			<Column Name="BUSINESS_HOUR_CODE" Label="时间" Type="INT" Display="YES" ContentStyle="NORMAL" HearderStyle="BOLD" />
			<Column Name="QUEUE_RATE" Label="费率(元/小时)" Type="INT" Display="YES" ContentStyle="NORMAL" HearderStyle="BOLD" />
			<Column Name="ROW_ID" Label="行号" Type="STRING" Display="NO" />
		</Outputs>
	</Select>
	<Variables>		
		<Variable Name="QUEUE_NAME" Target="QUEUE_NAME" Source="REQUEST" />
		<Variable Name="BUSINESS_HOUR_CODE" Target="BUSINESS_HOUR_CODE" Source="REQUEST" />
		<Variable Name="QUEUE_RATE" Target="QUEUE_RATE" Source="REQUEST" />			
		<Variable Name="ROW_ID" Target="ROW_ID" Source="REQUEST" />
					
		<Variable Name="QUEUE_MAP" Target="" Source="QUEUE_MAP_SOURCE" />
		
	</Variables>
	<Sources>
		<Source Name="REQUEST" Plug-in="com.platform.perf.report.config.var.source.RequestVariableSource" />
		<Source Name="QUEUE_MAP_SOURCE" Plug-in="com.platform.perf.report.config.var.source.SQLVaraibleSource">
			<Parameter Name="QUERIES">
				<Queries>
					<Query DBType="STANDARD">
						<SQL>
							<![CDATA[
							SELECT DISTINCT QUEUE_NAME AS QUEUE_CODE, QUEUE_NAME FROM QUEUE_NAME
						]]>
						</SQL>
					</Query>
				</Queries>
			</Parameter>
		</Source>
		
	</Sources>
</TableMaintenance>
