=== Lucho00Cuba/docker/symphony/shared/perf/conf/purger/purger.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:purger="http://www.ibm.com/perf/2006/06/purger" targetNamespace="http://www.ibm.com/perf/2006/06/purger" elementFormDefault="qualified">
	<xs:element name="PurgerConf">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Description" type="xs:string" minOccurs="0"/>
				<xs:element name="DataSource" type="xs:string"/>
				<xs:element name="TableList">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Table" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="TableName" type="xs:string" use="required"/>
									<xs:attribute name="TimestampColumn" type="xs:string" use="required"/>
									<xs:attribute name="Archive" type="xs:boolean" use="optional"/>
									<xs:attribute name="ClusterNameColumn" type="xs:string" use="optional"/>
									<xs:attribute name="Duration" use="optional">
										<xs:simpleType>
											<xs:restriction base="xs:integer">
												<xs:minInclusive value="0"/>
												<xs:maxInclusive value="365"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="Plug-in" type="xs:string" use="optional"/>
									<xs:attribute name="UseIndex" type="xs:string" use="optional"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="Duration" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:integer">
									<xs:minInclusive value="0"/>
									<xs:maxInclusive value="365"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Lucho00Cuba/docker/symphony/shared/perf/conf/purger/purger_ego.xml
<?xml version="1.0"?>
<PurgerConf xmlns="http://www.ibm.com/perf/2006/06/purger" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.ibm.com/perf/2006/06/purger purger.xsd">
    <!-- Specify the name of the current data source. -->
	<DataSource>ReportDB</DataSource>
	<!--
	The list of tables used to purge the database:

	Duration 	Required. The duration of the saved records, in days.
	-->
	<TableList Duration="14">
	 	<!--
		Each table implementation:

		TableName  		Required. The table name in the database.
		TimestampColumn		Required. The column name in the table.
					Its data type is Timestamp.
		Duration		Optional. Duration of the records in the table.
					If unspecified, the TableList duration is used.
		Archive			Required. Enables the backup of the data records
					into a zip file before purging the database. If false,
					the data records are not archived before purging the
					database.
		ClusterNameColumn	Optional. To purge records stored in the database
					for the current cluster, specify the name of the cluster for this table.
					The cluster name only applies to this particular table. 
		-->
		<Table TableName="ALLOCATION_EVENT" TimestampColumn="EVENT_TIME"  Archive="false"/>
		<Table TableName="CONSUMER_DEMAND" TimestampColumn="TIME_STAMP" Archive="false"/>
		<Table TableName="RESOURCE_METRICS" TimestampColumn="TIME_STAMP" Archive="false"/>
		<Table TableName="RESOURCE_ATTRIBUTES" TimestampColumn="TIME_STAMP" Archive="false"/>
		<Table TableName="CONSUMER_RESOURCE_ALLOCATION" TimestampColumn="TIME_STAMP" Archive="false"/>
		<Table TableName="CONSUMER_RESOURCELIST" TimestampColumn="TIME_STAMP" Archive="false"/>
		<Table TableName="CONSUMER_PLAN_NON_LEAF" TimestampColumn="TIME_STAMP" Archive="false"/>
		<Table TableName="DATALOADER_HEALTH" TimestampColumn="TIME_STAMP" Archive="false"/>
	</TableList>
</PurgerConf>
