=== Lucho00Cuba/docker/symphony/shared/gui/conf/help/pmc_help.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="http://www.platform.com/gui/pmc_help" 
	xmlns:tns="http://www.platform.com/gui/pmc_help" 
	elementFormDefault="qualified">

    <element name="HelpGroups" type="tns:HelpGroupsType"></element>
    
    <complexType name="HelpGroupsType">
    	<sequence>
    		<element name="HelpGroup" type="tns:HelpGroupType" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <complexType name="HelpGroupType">
    	<sequence>
    		<element name="Help" type="tns:HelpType" minOccurs="0"
    			maxOccurs="unbounded">
    		</element>
    	</sequence>
    	<attribute name="id" type="string"></attribute>
    	<attribute name="navigationId" type="string"></attribute>
    	<attribute name="url" type="string"></attribute>
    	<attribute name="role" type="string"></attribute>
    	<attribute name="urlPrefix" type="string" default="false"></attribute>
    	<attribute name="width" type="string"></attribute>
    	<attribute name="height" type="string"></attribute>
    </complexType>

    <complexType name="HelpType">
    	<attribute name="id" type="string"></attribute>
    	<attribute name="value" type="string"></attribute>
    	<attribute name="display" type="string"></attribute>
    	<attribute name="url" type="string"></attribute>
    	<attribute name="role" type="string"></attribute>
    	<attribute name="status" type="string"></attribute>
    	<attribute name="urlPrefix" type="string" default="false"></attribute>
    	<attribute name="width" type="string"></attribute>
    	<attribute name="height" type="string"></attribute>
    </complexType>
</schema>

=== Lucho00Cuba/docker/symphony/shared/gui/conf/help/pmc_help.xml
<?xml version="1.0" encoding="UTF-8"?>
<HelpGroups xmlns="http://www.platform.com/gui/pmc_help"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.platform.com/gui/pmc_help pmc_help.xsd">
	
	<HelpGroup id="egoservice" role="" url="/knowledgecenter/SSZUMP_7.3.2/help/admin/control_services.html" width="1280" height="720" urlPrefix="true">
		<Help role="" display="Service properties" url="/knowledgecenter/SSZUMP_7.3.2/shared_files/service_properties.html" width="1280" height="720" urlPrefix="true"/>
		<Help role="" display="Service Instances" url="/knowledgecenter/SSZUMP_7.3.2/shared_files/service_instances.html" width="1280" height="720" 
urlPrefix="true"/>
		<Help role="" display="Service profile" url="/knowledgecenter/SSZUMP_7.3.2/shared_files/service_profile.html" width="1280" height="720"  
urlPrefix="true"/>
		<Help role="" display="IBM Documentation" url="/knowledgecenter/SSZUMP_7.3.2/sym_kc_welcome.html" width="1280" height="720" urlPrefix="true"/>
		<Help role="" display="About" url="/platform/gotoAbout.controller?csrftoken=${csrftoken}"   width="500" height="650"/>
	</HelpGroup>
	
	<HelpGroup id="hostSoftware" role="" url="/knowledgecenter/SSZUMP_7.3.2/install_grid_sym/host_installed_active_software.html" width="1280" height="720" urlPrefix="true">
		<Help role="" display="Host Components" url="/knowledgecenter/SSZUMP_7.3.2/install_grid_sym/host_installed_active_software.html" width="1280" height="720" urlPrefix="true"/>
		<Help role="" display="IBM Documentation" url="/knowledgecenter/SSZUMP_7.3.2/sym_kc_welcome.html" width="1280" height="720" urlPrefix="true"/>
		<Help role="" display="About" url="/platform/gotoAbout.controller?csrftoken=${csrftoken}"   width="500" height="650"/>
	</HelpGroup>
	
	<HelpGroup id="egoserviceprofile" role="" url="/knowledgecenter/SSZUMP_7.3.2/help/admin/control_services.html" width="1280" height="720" urlPrefix="true">
		<Help role="" display="Service Profiles" url="/knowledgecenter/SSZUMP_7.3.2/help/admin/control_services.html" width="1280" height="720" urlPrefix="true" />
		<Help role="" display="IBM Documentation" url="/knowledgecenter/SSZUMP_7.3.2/sym_kc_welcome.html" width="1280" height="720" urlPrefix="true"/>
		<Help role="" display="About" url="/platform/gotoAbout.controller?csrftoken=${csrftoken}"   width="500" height="650"/>
	</HelpGroup>
	
	<HelpGroup id="egoservicegroup" role="" url="/knowledgecenter/SSZUMP_7.3.2/shared_files/service_group_concept.html" width="1280" height="720" urlPrefix="true">
		<Help role="" display="Service Groups" url="/knowledgecenter/SSZUMP_7.3.2/shared_files/service_group_concept.html" width="1280" height="720" urlPrefix="true" />
		<Help role="" display="Create Service Group" url="/knowledgecenter/SSZUMP_7.3.2/shared_files/service_group_create.html" width="1280" height="720" urlPrefix="true"/>
		<Help role="" display="Modify Service Group" url="/knowledgecenter/SSZUMP_7.3.2/shared_files/service_group_modify.html" width="1280" height="720" urlPrefix="true"/>
		<Help role="" display="Delete Service Group" url="/knowledgecenter/SSZUMP_7.3.2/shared_files/service_group_delete.html" width="1280" height="720" urlPrefix="true"/>
		<Help role="" display="View Service Details in Group" url="/knowledgecenter/SSZUMP_7.3.2/shared_files/service_group_service_details_view.html" width="1280" height="720" urlPrefix="true" />
		<Help role="" display="Start/Stop Services By Group" url="/knowledgecenter/SSZUMP_7.3.2/shared_files/service_group_start_stop_services.html" width="1280" height="720"  urlPrefix="true"/>
		<Help role="" display="IBM Documentation" url="/knowledgecenter/SSZUMP_7.3.2/sym_kc_welcome.html" width="1280" height="720" urlPrefix="true"/>
		<Help role="" display="About" url="/platform/gotoAbout.controller?csrftoken=${csrftoken}"   width="500" height="650"/>
	</HelpGroup>
	
	<HelpGroup id="resHosts" role="" url="/knowledgecenter/SSZUMP_7.3.2/shared_files/host_view.html" width="1280" height="720" urlPrefix="true">
		<Help role="" display="Hosts List View" url="/knowledgecenter/SSZUMP_7.3.2/shared_files/host_view.html" width="1280" height="720" urlPrefix="true"/>
		<Help role="" display="Hosts Icon View" url="/knowledgecenter/SSZUMP_7.3.2/shared_files/host_information_console.html" width="1280" height="720" urlPrefix="true" />
	    <Help role="" display="IBM Documentation" url="/knowledgecenter/SSZUMP_7.3.2/sym_kc_welcome.html" width="1280" height="720"  urlPrefix="true"/>	
	    <Help role="" display="About" url="/platform/gotoAbout.controller?csrftoken=${csrftoken}"   width="500" height="650"/>
	</HelpGroup>
		
	<HelpGroup id="resCloudRequest" role="" url="/knowledgecenter/SSZUMP_7.3.0/cloud_enablement/host_factory.html" width="1280" height="720" urlPrefix="true">
		<Help role="" display=" Viewing scheduled cloud requests and request instances" url="/knowledgecenter/SSZUMP_7.3.2/cloud_enablement/monitor_hostfactory_viewing_scheduled_requests.html" width="1280" height="720" urlPrefix="true" />
	    <Help role="" display="IBM Documentation" url="/knowledgecenter/SSZUMP_7.3.0/sym_kc_welcome.html" width="1280" height="720"  urlPrefix="true"/>	
	    <Help role="" display="About" url="/platform/gotoAbout.controller?csrftoken=${csrftoken}"   width="500" height="650"/>
	</HelpGroup>
	
	<HelpGroup id="resCloudHost" role="" url="/knowledgecenter/SSZUMP_7.3.2/cloud_enablement/host_factory.html" width="1280" height="720" urlPrefix="true">
		<Help role="" display="View hosts" url="/knowledgecenter/SSZUMP_7.3.2/cloud_enablement/monitor_hostfactory_viewing_provhosts.html" width="1280" height="720" urlPrefix="true" />
		<Help role="" display="Return host" url="/knowledgecenter/SSZUMP_7.3.2/cloud_enablement/manual_provisioning_return_hosts.html" width="1280" height="720" urlPrefix="true"/>
	    <Help role="" display="IBM Documentation" url="/knowledgecenter/SSZUMP_7.3.2/sym_kc_welcome.html" width="1280" height="720"  urlPrefix="true"/>	
	    <Help role="" display="About" url="/platform/gotoAbout.controller?csrftoken=${csrftoken}"   width="500" height="650"/>
	</HelpGroup>
	
	<HelpGroup id="resCloudConfiguration" role="" url="/knowledgecenter/SSZUMP_7.3.2/cloud_enablement/host_factory.html" width="1280" height="720" urlPrefix="true">
		<Help role="" display="Host Factory for cloud bursting" url="/knowledgecenter/SSZUMP_7.3.2/cloud_enablement/host_factory.html" width="1280" height="720" urlPrefix="true"/>
		<Help role="" display="Dynamic Configuration Update" url="/knowledgecenter/SSZUMP_7.3.2/cloud_enablement/host_factory_update_config.html" width="1280" height="720" urlPrefix="true" />
	    <Help role="" display="IBM Documentation" url="/knowledgecenter/SSZUMP_7.3.2/sym_kc_welcome.html" width="1280" height="720"  urlPrefix="true"/>	
	    <Help role="" display="About" url="/platform/gotoAbout.controller?csrftoken=${csrftoken}"   width="500" height="650"/>
	</HelpGroup>
	
	<HelpGroup id="rackivew" role="" url="/knowledgecenter/SSZUMP_7.3.2/mapreduce_user/mr_rack_view.html" width="1280" height="720" urlPrefix="true">
		<Help role="" display="Rack View" url="/knowledgecenter/SSZUMP_7.3.2/mapreduce_user/mr_rack_view.html" width="1280" height="720" urlPrefix="true"/>
		<Help role="" display="IBM Documentation" url="/knowledgecenter/SSZUMP_7.3.2/sym_kc_welcome.html" width="1000" height="700" urlPrefix="true"/>
		<Help role="" display="About" url="/platform/gotoAbout.controller?csrftoken=${csrftoken}"   width="500" height="650"/>
	</HelpGroup>
	
	<HelpGroup id="hdfs" role="" url="/knowledgecenter/SSZUMP_7.3.2/shared_files/mr_hdfs.html" width="1280" height="720" urlPrefix="true">
	    <Help role="" display="HDFS" url="/knowledgecenter/SSZUMP_7.3.2/shared_files/mr_hdfs.html" width="1280" height="720" urlPrefix="true"/>
		<Help role="" display="IBM Documentation" url="/knowledgecenter/SSZUMP_7.3.2/sym_kc_welcome.html" width="1000" height="700" urlPrefix="true"/>
		<Help role="" display="About" url="/platform/gotoAbout.controller?csrftoken=${csrftoken}"   width="500" height="650" urlPrefix="true"/>
	</HelpGroup>
	
	<HelpGroup id="resGroup" role="" url="/knowledgecenter/SSZUMP_7.3.2/shared_files/resource_groups.html" width="1280" height="720" urlPrefix="true">
		<Help role="" display="Resource Groups" url="/knowledgecenter/SSZUMP_7.3.2/shared_files/resource_groups.html" width="1280" height="720" urlPrefix="true"/>
		<Help role="" display="IBM Documentation" url="/knowledgecenter/SSZUMP_7.3.2/sym_kc_welcome.html" width="1000" height="700" urlPrefix="true"/>
		<Help role="" display="About" url="/platform/gotoAbout.controller?csrftoken=${csrftoken}"   width="500" height="650"/>
	</HelpGroup>
	<HelpGroup id="resGroupProp" role="" url="/knowledgecenter/SSZUMP_7.3.2/shared_files/resource_groups.html" width="1280" height="720" urlPrefix="true">
		<Help role="" display="Properties" url="/knowledgecenter/SSZUMP_7.3.2/help/admin/create_resource_groups_select.html" width="1280" height="720" urlPrefix="true" />
		<Help role="" display="IBM Documentation" url="/knowledgecenter/SSZUMP_7.3.2/sym_kc_welcome.html" width="1000" height="700" urlPrefix="true"/>
		<Help role="" display="About" url="/platform/gotoAbout.controller?csrftoken=${csrftoken}"   width="500" height="650"/>
	</HelpGroup>
	
	<HelpGroup id="resConsumer" role="" url="/knowledgecenter/SSZUMP_7.3.2/shared_files/tree_building.html" width="1000" height="700" urlPrefix="true">
		<Help role="" display="Consumers" url="/knowledgecenter/SSZUMP_7.3.2/shared_files/tree_building.html" width="1000" height="700" urlPrefix="true"/>
		<Help role="" display="IBM Documentation" url="/knowledgecenter/SSZUMP_7.3.2/sym_kc_welcome.html" width="1000" height="700" urlPrefix="true"/>
		<Help role="" display="About" url="/platform/gotoAbout.controller?csrftoken=${csrftoken}"   width="500" height="650"/>
	</HelpGroup>
	
	<HelpGroup id="resPlan" role="" url="/knowledgecenter/SSZUMP_7.3.2/shared_files/resource_plan_default.html" width="1000" height="700" urlPrefix="true">
